import { defineMessages, messagesOf } from '../../i18n';

/*
 * 「?」浮层三段文案·体重体成分与饮食域（D6）。
 *
 * 来源事实（v3-plan §4）：官方授权会同步体重（含 BMI 与身高资料值）；
 * 体脂率等体成分字段只有「高级数据」的体脂秤，官方 bodyComps 标 [Upcoming] 未开通；
 * 饮食是 Zepp App 手动记录，官方 nutrition 同样未开通。
 */

const messages = defineMessages(
  {
    weightWhat: '体重：每次称重的读数。',
    weightChart: '一天称多次时按天取平均，阴影是当天的实测区间。',
    weightHow: '称重记录来自 Zepp 云端——官方授权与「高级数据」都会同步；手表记的体重也在内，但带不来体脂成分。',
    bmiWhat: 'BMI：体重相对身高的比值（kg/m²）。',
    bmiChart: '随每次称重一起更新。',
    bmiHow: '云端随体重记录一起给出（官方授权与「高级数据」都有），不是本机按身高体重现算。',
    body_fat_rateWhat: '体脂率：脂肪占体重的比例，%。',
    body_fat_rateChart: '随每次体脂称重更新，一天多次时按天取平均。',
    body_fat_rateHow: '需要体脂秤——手表和手动录入的体重带不来这一项，经「高级数据」同步；官方的体成分接口尚未开通。',
    muscle_massWhat: '肌肉量，单位跟随你选的单位制。',
    muscle_massChart: '随每次体脂称重更新。',
    muscle_massHow: '需要体脂秤，经「高级数据」同步；官方的体成分接口尚未开通。',
    body_water_rateWhat: '体水分率：水分占体重的比例，%。',
    body_water_rateChart: '随每次体脂称重更新。',
    body_water_rateHow: '需要体脂秤，经「高级数据」同步；官方的体成分接口尚未开通。',
    bone_massWhat: '骨量，单位跟随你选的单位制。',
    bone_massChart: '随每次体脂称重更新。',
    bone_massHow: '需要体脂秤，经「高级数据」同步；官方的体成分接口尚未开通。',
    visceral_fatWhat: '内脏脂肪：腹腔内脂肪的等级，不是百分比。',
    visceral_fatChart: '随每次体脂称重更新。',
    visceral_fatHow: 'Zepp 的口径是 1–30 的等级，需要体脂秤，经「高级数据」同步。',
    bmrWhat: '基础代谢：静息状态下每天消耗的热量（千卡/天）。',
    bmrChart: '随每次体脂称重更新。',
    bmrHow: '需要体脂秤，经「高级数据」同步；官方的体成分接口尚未开通。',
    heightWhat: '身高：资料值，不是当次测量。',
    heightChart: '随每条称重记录一起回传，基本不变。',
    heightHow: '云端资料随称重记录回传（官方授权与「高级数据」都会同步）。',
    intake_caloriesWhat: '摄入热量：当天手动记录的总热量。',
    intake_caloriesChart: '按天画柱；没记的日子不画柱子，也不补 0。',
    intake_caloriesHow: '在 Zepp App 里手动记录，经「高级数据」同步——官方的营养接口尚未开通。',
    intake_protein_gWhat: '蛋白质：当天手动记录的总量（克）。',
    intake_protein_gChart: '按天画柱；没记的日子不画柱子，也不补 0。',
    intake_protein_gHow: '在 Zepp App 里手动记录，经「高级数据」同步——官方的营养接口尚未开通。',
    intake_fat_gWhat: '脂肪：当天手动记录的总量（克）。',
    intake_fat_gChart: '按天画柱；没记的日子不画柱子，也不补 0。',
    intake_fat_gHow: '在 Zepp App 里手动记录，经「高级数据」同步——官方的营养接口尚未开通。',
    intake_carbs_gWhat: '碳水：当天手动记录的总量（克）。',
    intake_carbs_gChart: '按天画柱；没记的日子不画柱子，也不补 0。',
    intake_carbs_gHow: '在 Zepp App 里手动记录，经「高级数据」同步——官方的营养接口尚未开通。',
  },
  {
    weightWhat: 'Body weight: one reading per weigh-in.',
    weightChart: 'Several weigh-ins in a day are averaged per day; the shaded band is that day’s measured range.',
    weightHow: 'Weigh-ins come from the Zepp cloud — both the official authorization and advanced data sync them; watch-recorded weight is included, but it carries no body composition.',
    bmiWhat: 'BMI: weight relative to height (kg/m²).',
    bmiChart: 'Updates with each weigh-in.',
    bmiHow: 'Sent by the cloud alongside the weight record (both the official authorization and advanced data) — not computed here from height and weight.',
    body_fat_rateWhat: 'Body fat: fat as a share of weight, in %.',
    body_fat_rateChart: 'Updates with each body-composition weigh-in; several in a day are averaged per day.',
    body_fat_rateHow: 'Needs a body-composition scale — watch and hand-entered weights carry none of this. Synced via advanced data; the official body-composition API is not open yet.',
    muscle_massWhat: 'Muscle mass, shown in your chosen unit system.',
    muscle_massChart: 'Updates with each body-composition weigh-in.',
    muscle_massHow: 'Needs a body-composition scale, synced via advanced data; the official body-composition API is not open yet.',
    body_water_rateWhat: 'Body water: water as a share of weight, in %.',
    body_water_rateChart: 'Updates with each body-composition weigh-in.',
    body_water_rateHow: 'Needs a body-composition scale, synced via advanced data; the official body-composition API is not open yet.',
    bone_massWhat: 'Bone mass, shown in your chosen unit system.',
    bone_massChart: 'Updates with each body-composition weigh-in.',
    bone_massHow: 'Needs a body-composition scale, synced via advanced data; the official body-composition API is not open yet.',
    visceral_fatWhat: 'Visceral fat: a grade of the fat around the internal organs, not a percentage.',
    visceral_fatChart: 'Updates with each body-composition weigh-in.',
    visceral_fatHow: 'Zepp scores it as a 1–30 grade. Needs a body-composition scale, synced via advanced data.',
    bmrWhat: 'Basal metabolism: the daily burn at complete rest (kcal/day).',
    bmrChart: 'Updates with each body-composition weigh-in.',
    bmrHow: 'Needs a body-composition scale, synced via advanced data; the official body-composition API is not open yet.',
    heightWhat: 'Height: a profile value, not a measurement of the day.',
    heightChart: 'Echoed back with every weigh-in; rarely changes.',
    heightHow: 'Profile data from the cloud, sent along with each weigh-in (both the official authorization and advanced data).',
    intake_caloriesWhat: 'Calories eaten: the total logged for the day.',
    intake_caloriesChart: 'Drawn as one bar per day; days with nothing logged get no bar and are never zero-filled.',
    intake_caloriesHow: 'Logged by hand in the Zepp App, synced via advanced data — the official nutrition API is not open yet.',
    intake_protein_gWhat: 'Protein: the total logged for the day, in grams.',
    intake_protein_gChart: 'Drawn as one bar per day; days with nothing logged get no bar and are never zero-filled.',
    intake_protein_gHow: 'Logged by hand in the Zepp App, synced via advanced data — the official nutrition API is not open yet.',
    intake_fat_gWhat: 'Fat: the total logged for the day, in grams.',
    intake_fat_gChart: 'Drawn as one bar per day; days with nothing logged get no bar and are never zero-filled.',
    intake_fat_gHow: 'Logged by hand in the Zepp App, synced via advanced data — the official nutrition API is not open yet.',
    intake_carbs_gWhat: 'Carbs: the total logged for the day, in grams.',
    intake_carbs_gChart: 'Drawn as one bar per day; days with nothing logged get no bar and are never zero-filled.',
    intake_carbs_gHow: 'Logged by hand in the Zepp App, synced via advanced data — the official nutrition API is not open yet.',
  },
  {
    weightWhat: 'Peso corporal: una lectura por pesaje.',
    weightChart: 'Varios pesajes en un día se promedian por día; la banda es el rango medido ese día.',
    weightHow: 'Los pesajes vienen de la nube de Zepp — la autorización oficial y los datos avanzados los sincronizan; el peso registrado por el reloj también entra, pero no trae composición corporal.',
    bmiWhat: 'IMC: el peso en relación con la estatura (kg/m²).',
    bmiChart: 'Se actualiza con cada pesaje.',
    bmiHow: 'Lo da la nube junto con el registro de peso (autorización oficial y datos avanzados); no se calcula aquí con estatura y peso.',
    body_fat_rateWhat: 'Grasa corporal: la grasa como proporción del peso, en %.',
    body_fat_rateChart: 'Se actualiza con cada pesaje de composición; varios en un día se promedian por día.',
    body_fat_rateHow: 'Requiere una báscula de composición corporal — el peso del reloj o anotado a mano no la trae. Se sincroniza por los datos avanzados; la API oficial de composición aún no está abierta.',
    muscle_massWhat: 'Masa muscular, en el sistema de unidades que elijas.',
    muscle_massChart: 'Se actualiza con cada pesaje de composición.',
    muscle_massHow: 'Requiere una báscula de composición, por los datos avanzados; la API oficial aún no está abierta.',
    body_water_rateWhat: 'Agua corporal: el agua como proporción del peso, en %.',
    body_water_rateChart: 'Se actualiza con cada pesaje de composición.',
    body_water_rateHow: 'Requiere una báscula de composición, por los datos avanzados; la API oficial aún no está abierta.',
    bone_massWhat: 'Masa ósea, en el sistema de unidades que elijas.',
    bone_massChart: 'Se actualiza con cada pesaje de composición.',
    bone_massHow: 'Requiere una báscula de composición, por los datos avanzados; la API oficial aún no está abierta.',
    visceral_fatWhat: 'Grasa visceral: un nivel de la grasa alrededor de los órganos, no un porcentaje.',
    visceral_fatChart: 'Se actualiza con cada pesaje de composición.',
    visceral_fatHow: 'Zepp la califica de 1 a 30. Requiere una báscula de composición, por los datos avanzados.',
    bmrWhat: 'Metabolismo basal: lo que quemas en reposo cada día (kcal/día).',
    bmrChart: 'Se actualiza con cada pesaje de composición.',
    bmrHow: 'Requiere una báscula de composición, por los datos avanzados; la API oficial aún no está abierta.',
    heightWhat: 'Estatura: un dato del perfil, no una medición del día.',
    heightChart: 'Vuelve con cada pesaje; casi no cambia.',
    heightHow: 'Dato del perfil en la nube, devuelto con cada pesaje (autorización oficial y datos avanzados).',
    intake_caloriesWhat: 'Calorías consumidas: el total registrado en el día.',
    intake_caloriesChart: 'Una barra por día; los días sin registro no tienen barra y nunca se rellenan con 0.',
    intake_caloriesHow: 'Se anota a mano en la app Zepp y se sincroniza por los datos avanzados; la API oficial de nutrición aún no está abierta.',
    intake_protein_gWhat: 'Proteína: el total registrado en el día, en gramos.',
    intake_protein_gChart: 'Una barra por día; los días sin registro no tienen barra y nunca se rellenan con 0.',
    intake_protein_gHow: 'Se anota a mano en la app Zepp y se sincroniza por los datos avanzados; la API oficial de nutrición aún no está abierta.',
    intake_fat_gWhat: 'Grasa: el total registrado en el día, en gramos.',
    intake_fat_gChart: 'Una barra por día; los días sin registro no tienen barra y nunca se rellenan con 0.',
    intake_fat_gHow: 'Se anota a mano en la app Zepp y se sincroniza por los datos avanzados; la API oficial de nutrición aún no está abierta.',
    intake_carbs_gWhat: 'Carbohidratos: el total registrado en el día, en gramos.',
    intake_carbs_gChart: 'Una barra por día; los días sin registro no tienen barra y nunca se rellenan con 0.',
    intake_carbs_gHow: 'Se anota a mano en la app Zepp y se sincroniza por los datos avanzados; la API oficial de nutrición aún no está abierta.',
  },
  // moduleId：让 src/i18n/locales/<locale>.ts 的语言包能覆盖这个模块。
  'lib/metricInfo/body',
);

export const BODY_METRICS = [
  'weight',
  'bmi',
  'body_fat_rate',
  'muscle_mass',
  'body_water_rate',
  'bone_mass',
  'visceral_fat',
  'bmr',
  'height',
  'intake_calories',
  'intake_protein_g',
  'intake_fat_g',
  'intake_carbs_g',
] as const;

/** 按指标 id 取三段文案；认不出的 id 返回 null。 */
export const bodyInfo = (metric: string): { what: string; chart: string; how: string } | null => {
  if (!(BODY_METRICS as readonly string[]).includes(metric)) return null;
  const t = messagesOf(messages) as Record<string, string>;
  return {
    what: t[`${metric}What`],
    chart: t[`${metric}Chart`],
    how: t[`${metric}How`],
  };
};
