import type { LandingLocale } from '../composables/useLandingLocale';
// The conversation is a scripted local example. These strings never come from an AI service.
const labels: Record<LandingLocale, string[]> = {
  zh: ['发送', '正在整理记录', '计划已整理好', '复制计划', '正在接回计划', '返回', '示例对话', '保留休息日，整理成可以接回的 Plan。', '已将训练日期、项目和步骤整理成 Plan。休息日保留为空白，不会用虚构记录补齐缺失的数据。\n\n接回 ZeppBridge 后，你可以逐日查看热身、训练和放松步骤，也可以拖动卡片交换日期。确认以后再决定是否发到手表。'],
  en: ['Send', 'Reading the records', 'Your plan is ready', 'Copy plan', 'Bringing the plan back', 'Back', 'Sample conversation', 'Keep the rest days and package this as a Plan I can bring back.', 'The Plan contains the dates, activities and steps. Rest days stay open, and missing measurements have not been filled with invented records.\n\nBack in ZeppBridge, review each warm-up, workout and cooldown. Drag a card to swap dates, then decide whether to send the plan to your watch.'],
  es: ['Enviar', 'Revisando los registros', 'El plan está listo', 'Copiar plan', 'Recuperando el plan', 'Volver', 'Conversación de ejemplo', 'Conserva los días de descanso y prepara un Plan para recuperar.', 'El Plan incluye fechas, actividades y pasos. Se conservan los descansos y no se inventan datos ausentes.\n\nEn ZeppBridge puedes revisar el calentamiento, el entrenamiento y la vuelta a la calma, cambiar las fechas y decidir si lo envías al reloj.'],
  fr: ['Envoyer', 'Lecture des données', 'Le plan est prêt', 'Copier le plan', 'Récupération du plan', 'Retour', 'Conversation d’exemple', 'Garde les jours de repos et prépare un Plan à récupérer.', 'Le Plan contient les dates, les activités et les étapes. Les repos sont conservés et aucune mesure manquante n’est inventée.\n\nDans ZeppBridge, vérifie l’échauffement, l’entraînement et le retour au calme. Déplace les cartes avant de décider de l’envoi à la montre.'],
  de: ['Senden', 'Aufzeichnungen werden gelesen', 'Der Plan ist fertig', 'Plan kopieren', 'Plan wird übernommen', 'Zurück', 'Beispielgespräch', 'Behalte die Ruhetage und erstelle einen Plan zum Übernehmen.', 'Der Plan enthält Termine, Aktivitäten und Schritte. Ruhetage bleiben erhalten und fehlende Messwerte werden nicht erfunden.\n\nIn ZeppBridge kannst du Aufwärmen, Training und Abkühlen prüfen. Verschiebe die Karten und entscheide anschließend, ob der Plan an die Uhr gesendet wird.'],
  nl: ['Versturen', 'Gegevens bekijken', 'Je plan is klaar', 'Plan kopiëren', 'Plan ophalen', 'Terug', 'Voorbeeldgesprek', 'Behoud de rustdagen en maak een Plan dat ik kan ophalen.', 'Het Plan bevat datums, activiteiten en stappen. Rustdagen blijven staan en ontbrekende metingen worden niet verzonnen.\n\nControleer in ZeppBridge de warming-up, training en cooling-down. Versleep kaarten om datums te wisselen en besluit daarna of je het plan naar je horloge stuurt.'],
  'pt-BR': ['Enviar', 'Lendo os registros', 'Seu plano está pronto', 'Copiar plano', 'Trazendo o plano de volta', 'Voltar', 'Conversa de exemplo', 'Mantenha os dias de descanso e prepare um Plan para trazer de volta.', 'O Plan contém datas, atividades e etapas. Os descansos são mantidos e medições ausentes não são inventadas.\n\nNo ZeppBridge, confira aquecimento, treino e desaquecimento. Arraste os cartões para trocar datas e depois decida se quer enviar ao relógio.'],
  'pt-PT': ['Enviar', 'A ler os registos', 'O plano está pronto', 'Copiar plano', 'A recuperar o plano', 'Voltar', 'Conversa de exemplo', 'Mantém os dias de descanso e prepara um Plan para recuperar.', 'O Plan contém datas, atividades e etapas. Os descansos são mantidos e as medições em falta não são inventadas.\n\nNo ZeppBridge, revê o aquecimento, o treino e o retorno à calma. Arrasta os cartões para trocar datas e decide se queres enviar o plano ao relógio.'],
  ru: ['Отправить', 'Чтение записей', 'План готов', 'Копировать план', 'Возвращаем план', 'Назад', 'Пример диалога', 'Сохрани дни отдыха и подготовь Plan для переноса обратно.', 'Plan содержит даты, занятия и этапы. Дни отдыха сохранены, пропущенные измерения не выдуманы.\n\nВ ZeppBridge можно проверить разминку, тренировку и заминку, переместить карточки между датами и решить, отправлять ли план на часы.'],
  'hi-IN': ['भेजें', 'रिकॉर्ड पढ़े जा रहे हैं', 'आपका प्लान तैयार है', 'प्लान कॉपी करें', 'प्लान वापस लाया जा रहा है', 'वापस', 'उदाहरण बातचीत', 'आराम के दिन रखें और वापस लाने के लिए Plan तैयार करें।', 'Plan में तारीखें, गतिविधियाँ और चरण हैं। आराम के दिन बने रहते हैं और गायब माप गढ़े नहीं जाते।\n\nZeppBridge में वार्म-अप, अभ्यास और कूल-डाउन देखें। तारीख बदलने के लिए कार्ड खींचें, फिर तय करें कि प्लान घड़ी पर भेजना है या नहीं।'],
};
export function dialogueCopy(locale: LandingLocale) {
  const [send, thinking, ready, copy, returning, back, example, prompt, answer] = labels[locale];
  return { send, thinking, ready, copy, returning, back, example, finalTurn: { prompt, answer } };
}
