import { DesktopUnavailableError } from './errors';
import type { BridgeBackend, UnlistenFn } from './types';

const unavailable = (): never => {
  throw new DesktopUnavailableError();
};

export const webBackend: BridgeBackend = {
  getAppStatus: unavailable,
  saveAuth: unavailable,
  verifyAuth: unavailable,
  clearAuth: unavailable,
  importFromHar: unavailable,
  manualAuth: unavailable,
  startWebLogin: unavailable,
  cancelWebLogin: unavailable,
  getLoginStatus: unavailable,
  startInitialSync: unavailable,
  startHistorySync: unavailable,
  startIncrementalSync: unavailable,
  cancelSync: unavailable,
  probeDataCapabilities: unavailable,
  getCapabilityOverview: unavailable,
  getHealthOverview: unavailable,
  getHeartRateSeries: unavailable,
  getTrainingLoadSeries: unavailable,
  getMetricSeries: unavailable,
  getTrainingBalance: unavailable,
  getHeartRateZones: unavailable,
  setHeartRateZonePreference: unavailable,
  getStorageEstimate: unavailable,
  setUserPrefs: unavailable,
  getUserPrefs: unavailable,
  getDailyHeartRateExtremes: unavailable,
  getRecentSleep: unavailable,
  getSleepPage: unavailable,
  getSleepDetail: unavailable,
  getRecentWorkouts: unavailable,
  getWorkoutPage: unavailable,
  getWorkoutDetail: unavailable,
  getWorkoutSeries: unavailable,
  setWorkoutTypeOverride: unavailable,
  getWorkoutTypeOptions: unavailable,
  getUnknownWorkoutCodes: unavailable,
  setWorkoutCodeLabel: unavailable,
  getDeviceCatalogOptions: unavailable,
  setDeviceModelOverride: unavailable,
  getLocalApiStatus: unavailable,
  setLocalApiEnabled: unavailable,
  revealLocalApiToken: unavailable,
  rotateLocalApiToken: unavailable,
  getDeviceProfile: unavailable,
  getDeviceProfiles: unavailable,
  reprocessLocalData: unavailable,
  getDiagnosticReport: unavailable,
  getWorkoutInsight: unavailable,
  getWeeklyReport: unavailable,
  startHistoryBackfill: unavailable,
  getCoverageLedger: unavailable,
  resetCoverageLedger: unavailable,
  retryFailedBackfillChunks: unavailable,
  setTrayLocale: unavailable,
  listBackups: unavailable,
  createManualBackup: unavailable,
  verifyBackup: unavailable,
  setBackupPinned: unavailable,
  getRestorePreview: unavailable,
  stageRestore: unavailable,
  getPendingRestore: unavailable,
  cancelPendingRestore: unavailable,
  getDataHealth: unavailable,
  runDatabaseIntegrityCheck: unavailable,
  compactRawPayloads: unavailable,
  submitDiagnosticReport: unavailable,
  submitDeviceModelAssignment: unavailable,
  getExportJson: unavailable,
  saveJsonExport: unavailable,
  saveCsvExport: unavailable,
  saveGpxExport: unavailable,
  publishAiExport: unavailable,
  prepareAiHandoff: unavailable,
  cleanupOldData: unavailable,
  openDataFolder: unavailable,
  listen<T>(_event: string, _handler: (payload: T) => void): Promise<UnlistenFn> {
    return Promise.resolve(() => undefined);
  },
};
