import type { LandingCopy } from './types';

/*
 * 落地页的中英文案（首屏即时，不等网络）。其余八种语言是同目录的懒加载语言包。
 * 英文是重写不是翻译：两边各按自己的语言写，只保证说的是同一件事。
 * 不用破折号；演示读数一律是示例。
 */
export const COPY: Record<'zh' | 'en', LandingCopy> = {
  zh: {
    nav: {
      home: 'ZeppBridge 首页',
      site: '网站导航',
      demo: '演示',
      features: '功能',
      ai: '交给 AI',
      privacy: '隐私',
      download: '下载',
      github: 'GitHub',
      language: '界面语言',
      toDark: '切换到深色',
      toLight: '切换到浅色',
    },
    downloads: {
      windows: { label: '下载 Windows 版', hint: 'x64 安装包', msi: '批量部署用 MSI' },
      macos: { label: '下载 macOS 版', hint: 'Apple Silicon' },
      linux: {
        label: 'Linux',
        previewBadge: '实验性',
        note: 'deb / rpm / AppImage / Flatpak 由 CI 构建，还没人在真实 Linux 桌面上完整跑通登录和密钥环。遇到问题请开 issue。',
      },
      status: {
        loading: '正在读取最新安装包',
        ready: '点击直接下载',
        fallback: '会打开 GitHub Releases 页面，在那里挑安装包',
      },
    },
    sample: '示例',
    hero: {
      eyebrow: '免费 · 开源 · 数据只在本机',
      titleLead: '从手腕，到你的电脑。',
      titleAccent: '从电脑，直接到 AI。',
      lead: 'ZeppBridge 把 Amazfit 记下的心率、睡眠、运动从 Zepp 云端同步到你自己的电脑，存成一份看得懂、带得走的本地档案；想问 AI 的时候，挑好范围，一个文件就交出去。',
      pillars: ['同步到你的电脑', '一键交给 AI'],
      github: '在 GitHub 上看源码',
      meta: '免费 · Windows 10 / 11 · macOS（Apple Silicon） · Linux 实验性',
      devices: '这些 Amazfit 设备都认得',
      toasts: [
        { title: '同步完成', body: '新增 1,284 条记录，最晚一条是今早 07:12' },
        { title: '昨晚睡眠 7 小时 12 分', body: '深睡比你过去 30 天的平均多 18 分钟' },
        { title: '已打包给 AI', body: '睡眠、心率、HRV，最近 7 天，一个 .md 文件' },
        { title: '傍晚跑步 6.2 公里', body: '有轨迹、有逐公里配速，也有心率曲线' },
        { title: '有 2 小时没有心率', body: '那段时间表不在手上，图上留空，不补 0' },
      ],
      ask: { question: '这周我睡得怎么样？和上周比呢？', file: 'ZeppBridge 最近7天.md' },
      starNudge: {
        title: '下载已经开始',
        copy: '觉得有用的话，去 GitHub 点个 Star，让更多 Amazfit 用户找到它。',
        action: '去点 Star',
        dismiss: '下次吧',
      },
    },
    chapters: { sync: '01 · 同步到电脑', ai: '02 · 交给 AI' },
    flap: {
      heading: '这些年，它一直在记',
      lead: '一块戴了三年的表，大概记下这么多。ZeppBridge 把它们一条条拉回来，按天排好。',
      tiles: [
        { value: '1,096', label: '个夜晚的睡眠' },
        { value: '742', label: '次运动，带轨迹' },
        { value: '1.5M', label: '个逐分钟心率' },
        { value: '9.8M', label: '步' },
      ],
    },
    demo: {
      heading: '像一个好用的 App，不像一张表格',
      lead: '点上面的标签换一种数据。再拨一下右边的开关，看看「没测到」应该怎么画。',
      window: 'ZeppBridge · 概览',
      tabs: { heart: '心率', sleep: '睡眠', steps: '步数' },
      nav: ['概览', '交给 AI', '运动', '设置'],
      heart: { value: '62', unit: '次/分', caption: '今天的逐分钟心率，傍晚那一段是跑步' },
      sleep: { value: '7 小时 12 分', caption: '昨晚 23:48 入睡，07:00 醒来', stages: ['清醒', 'REM', '浅睡', '深睡'] },
      steps: { value: '11,406', unit: '步', caption: '每小时步数，没走路的时段是空的' },
      gap: {
        label: '没戴表的那两小时',
        honest: '留空',
        zero: '补 0',
        honestNote: 'ZeppBridge 的画法：没有数据就是没有，曲线断开。',
        zeroNote: '很多工具会这样画：一条掉到 0 的线，看起来像你出了事。',
      },
    },
    bento: {
      heading: '该有的都在，没用的一样没加',
      lead: '每一块都在本机跑，不依赖我们的服务器。',
      connect: {
        title: '三条路接进来',
        copy: '官方授权打底，高级数据补指标，都不行还能手动填。',
        rows: ['Zepp 官方授权', '高级数据', '手动填写'],
        states: ['已连接', '已连接', '备用'],
      },
      local: { title: '一个文件夹就是全部', copy: '数据库就在程序旁边的 data 文件夹，复制走就是完整备份。' },
      export: { title: '想带去哪都行', copy: 'JSON、CSV、GPX、FIT，按你选的范围导出。' },
      api: {
        title: '给脚本和 AI 工具留了门',
        copy: '命令行、MCP、本机只读接口，默认关闭，只在 127.0.0.1。',
        output: ['数据库  正常', '最近同步  今天 07:12', '待补拉  0 天'],
      },
      languages: { title: '十种界面语言', copy: '中文、英文、西班牙文、德文、法文、荷兰文、两种葡萄牙文、俄文、印地文。' },
      theme: { title: '深色为主，浅色也有', copy: '跟着系统，或者自己挑。', dark: '深色', light: '浅色' },
    },
    ai: {
      heading: '想问 AI？先挑要给它看什么',
      lead: '勾上几类数据，ZeppBridge 打包成一个 .md 文件。拖进你平时用的 AI，像问一位看过你全部记录的朋友。',
      pick: '这次给 AI 看',
      chips: ['睡眠', '心率', 'HRV', '运动', '压力', '体重'],
      picked: '已选 {n} 类，最近 7 天',
      file: 'ZeppBridge 最近7天.md',
      prompt: '我这周是不是睡得比上周差？可能是什么原因？',
      answer: '是差一些：平均少了 38 分钟，主要少在深睡。周二、周四都有晚间训练，那两晚入睡后心率降得更慢。可以先把训练挪到下午试一周。',
      note: '不内置 AI，也不用另外注册账号。交什么、交多少、什么时候交，都是你点了才算。',
    },
    privacy: {
      heading: '你的健康数据，只在两个地方',
      lead: 'Zepp 的云端，和你自己的电脑。中间没有第三个。',
      nodes: { watch: '手表', cloud: 'Zepp 云端', computer: '你的电脑', server: 'ZeppBridge 服务器', none: '不存在' },
      points: [
        { title: '令牌进系统凭据库', copy: '放在 Windows 凭据管理器或 macOS 钥匙串，不写进数据文件夹。' },
        { title: '没有遥测', copy: '不统计你怎么用，不收集任何健康数据。' },
        { title: '来源分得清', copy: '每条记录都知道自己来自官方授权还是高级数据。' },
      ],
    },
    connect: {
      heading: '三种连接方式，挑顺手的那条',
      lead: '先用官方授权；想要更多指标，再加上高级数据。',
      recommended: '推荐',
      paths: [
        { title: 'Zepp 官方授权', copy: '在常用浏览器里登录 Zepp，点同意就连上。', detail: 'Google、小米、Apple 账号都能用。睡眠、心率、步数、运动、PAI、体重会同步。' },
        { title: '高级数据', copy: '补上官方没开放的 HRV、血氧、压力、准备度。', detail: '用邮箱或手机号登录，令牌只存在系统凭据库里。' },
        { title: '手动填写', copy: '前两条都用不了时的后备。', detail: '自己粘贴令牌，适合熟悉接口的人。' },
      ],
      note: '能同步到什么，取决于你的账号在 Zepp 云端存了什么；具体能看到哪些指标，取决于你的设备和用的连接方式。',
    },
    final: {
      heading: '装上，看看它这些年记了些什么',
      lead: '免费，开源，不用注册。',
      facts: {
        channel: '稳定版，安装包来自 GitHub Releases',
        systems: 'Windows 10 / 11（x64）和 macOS（Apple Silicon）；Linux 为实验性',
        ai: '不需要另外的账号，交给 AI 时用你自己平时用的那个',
        windows: 'Windows：安装包还没有代码签名，可能提示「未知发布者」，点「更多信息」再点「仍要运行」',
        macos: 'macOS：未签名版本，第一次打开会被拦下，放行步骤写在 GitHub 的说明里',
      },
    },
    footer: {
      tagline: '本地优先的 Amazfit / Zepp 数据桥梁。',
      disclaimer: 'ZeppBridge 是独立的开源项目，与 Zepp Health、Amazfit 没有隶属关系。',
      source: '源码',
    },
  },
  en: {
    nav: {
      home: 'ZeppBridge home',
      site: 'Site navigation',
      demo: 'Demo',
      features: 'Features',
      ai: 'AI handoff',
      privacy: 'Privacy',
      download: 'Download',
      github: 'GitHub',
      language: 'Language',
      toDark: 'Switch to dark',
      toLight: 'Switch to light',
    },
    downloads: {
      windows: { label: 'Download for Windows', hint: 'x64 installer', msi: 'MSI for managed installs' },
      macos: { label: 'Download for macOS', hint: 'Apple Silicon' },
      linux: {
        label: 'Linux',
        previewBadge: 'Experimental',
        note: 'deb, rpm, AppImage and Flatpak are built by CI, but nobody has run sign-in and the keyring end to end on a real Linux desktop yet. Hit a problem? Open an issue.',
      },
      status: {
        loading: 'Looking up the latest installer',
        ready: 'Click to download directly',
        fallback: 'Opens GitHub Releases, where you pick the installer',
      },
    },
    sample: 'Sample',
    hero: {
      eyebrow: 'Free · Open source · Stays on your machine',
      titleLead: 'From your wrist to your desk.',
      titleAccent: 'From your desk to your AI.',
      lead: 'ZeppBridge syncs the heart rate, sleep and workouts your Amazfit recorded from the Zepp cloud to your own computer as an archive you can read and carry anywhere. When you have a question, pick a range and hand it to an AI as a single file.',
      pillars: ['Synced to your computer', 'Handed to your AI'],
      github: 'Read the source on GitHub',
      meta: 'Free · Windows 10 / 11 · macOS (Apple Silicon) · Linux experimental',
      devices: 'Amazfit devices it already knows',
      toasts: [
        { title: 'Sync finished', body: '1,284 new records, the latest from 07:12 this morning' },
        { title: 'Slept 7 h 12 min', body: '18 minutes more deep sleep than your 30 day average' },
        { title: 'Packed for your AI', body: 'Sleep, heart rate and HRV, last 7 days, one .md file' },
        { title: 'Evening run, 6.2 km', body: 'Route, per kilometre pace and the heart rate curve' },
        { title: 'Two hours without heart rate', body: 'The watch was off your wrist. The chart stays empty, never zero.' },
      ],
      ask: { question: 'How did I sleep this week compared with last?', file: 'ZeppBridge last 7 days.md' },
      starNudge: {
        title: 'Your download has started',
        copy: 'If ZeppBridge helps, a star on GitHub helps other Amazfit owners find it.',
        action: 'Star on GitHub',
        dismiss: 'Maybe later',
      },
    },
    chapters: { sync: '01 · Synced to your computer', ai: '02 · Handed to your AI' },
    flap: {
      heading: 'It never stopped writing things down',
      lead: 'Three years on the wrist adds up to roughly this. ZeppBridge pulls every record back and lines them up by day.',
      tiles: [
        { value: '1,096', label: 'nights of sleep' },
        { value: '742', label: 'workouts with routes' },
        { value: '1.5M', label: 'minutes of heart rate' },
        { value: '9.8M', label: 'steps' },
      ],
    },
    demo: {
      heading: 'Feels like an app, not a spreadsheet',
      lead: 'Switch the tabs to see another kind of data. Then flip the switch and see how a missing reading should look.',
      window: 'ZeppBridge · Overview',
      tabs: { heart: 'Heart rate', sleep: 'Sleep', steps: 'Steps' },
      nav: ['Overview', 'AI handoff', 'Workouts', 'Settings'],
      heart: { value: '62', unit: 'bpm', caption: 'Minute by minute today. The evening spike is a run.' },
      sleep: { value: '7 h 12 min', caption: 'Asleep at 23:48, awake at 07:00', stages: ['Awake', 'REM', 'Light', 'Deep'] },
      steps: { value: '11,406', unit: 'steps', caption: 'Steps per hour. Hours without walking stay empty.' },
      gap: {
        label: 'Two hours off the wrist',
        honest: 'Leave empty',
        zero: 'Fill with 0',
        honestNote: 'How ZeppBridge draws it: no data means no data, so the line breaks.',
        zeroNote: 'How plenty of tools draw it: a drop to zero that looks like an emergency.',
      },
    },
    bento: {
      heading: 'Everything it needs. Nothing it does not.',
      lead: 'Every piece runs on your machine, with no server of ours in the loop.',
      connect: {
        title: 'Three ways in',
        copy: 'Official authorization first, advanced data for extra metrics, manual entry as the fallback.',
        rows: ['Zepp official authorization', 'Advanced data', 'Manual entry'],
        states: ['Connected', 'Connected', 'Standby'],
      },
      local: { title: 'One folder is everything', copy: 'The database sits in a data folder next to the app. Copy it and you have a full backup.' },
      export: { title: 'Take it anywhere', copy: 'JSON, CSV, GPX and FIT, for whatever range you choose.' },
      api: {
        title: 'A door for scripts and AI tools',
        copy: 'Command line, MCP and a local read-only API. Off by default, 127.0.0.1 only.',
        output: ['database   ok', 'last sync  today 07:12', 'backfill   0 days left'],
      },
      languages: { title: 'Ten interface languages', copy: 'English, Chinese, Spanish, German, French, Dutch, two kinds of Portuguese, Russian and Hindi.' },
      theme: { title: 'Dark first, light too', copy: 'Follow the system or pick your own.', dark: 'Dark', light: 'Light' },
    },
    ai: {
      heading: 'Asking an AI? Choose what it gets to see.',
      lead: 'Tick a few kinds of data and ZeppBridge packs them into one .md file. Drop it into the AI you already use and ask like you would a friend who read every record.',
      pick: 'For the AI this time',
      chips: ['Sleep', 'Heart rate', 'HRV', 'Workouts', 'Stress', 'Weight'],
      picked: '{n} kinds picked, last 7 days',
      file: 'ZeppBridge last 7 days.md',
      prompt: 'Did I sleep worse this week than last? What might be behind it?',
      answer: 'A little worse: 38 minutes less on average, mostly deep sleep. Tuesday and Thursday had evening training, and on those nights your heart rate took longer to settle. Try moving training to the afternoon for a week.',
      note: 'No built-in AI and no extra account. What goes out, how much and when only happens when you click.',
    },
    privacy: {
      heading: 'Your health data lives in two places',
      lead: 'The Zepp cloud and your own computer. There is no third.',
      nodes: { watch: 'Watch', cloud: 'Zepp cloud', computer: 'Your computer', server: 'ZeppBridge server', none: 'does not exist' },
      points: [
        { title: 'Tokens in the system vault', copy: 'Kept in Windows Credential Manager or the macOS Keychain, never in the data folder.' },
        { title: 'No telemetry', copy: 'No usage tracking and no health data collected.' },
        { title: 'Clear provenance', copy: 'Every record knows whether it came from the official authorization or advanced data.' },
      ],
    },
    connect: {
      heading: 'Three ways to connect. Pick the easy one.',
      lead: 'Start with the official authorization. Add advanced data when you want more metrics.',
      recommended: 'Recommended',
      paths: [
        { title: 'Zepp official authorization', copy: 'Sign in to Zepp in your usual browser and approve.', detail: 'Google, Xiaomi and Apple accounts work. Sleep, heart rate, steps, workouts, PAI and weight sync.' },
        { title: 'Advanced data', copy: 'Adds HRV, blood oxygen, stress and readiness, which the official API does not offer.', detail: 'Sign in with email or phone. The token lives only in your system vault.' },
        { title: 'Manual entry', copy: 'The fallback when neither of the others works.', detail: 'Paste a token yourself. Meant for people who know the API.' },
      ],
      note: 'What syncs depends on what your account holds in the Zepp cloud. Which metrics you see depends on your device and the way you connect.',
    },
    final: {
      heading: 'Install it and see what your watch remembers',
      lead: 'Free, open source, no sign-up.',
      facts: {
        channel: 'Stable channel, installers from GitHub Releases',
        systems: 'Windows 10 / 11 (x64) and macOS (Apple Silicon). Linux is experimental.',
        ai: 'No extra account needed. For AI questions you use the one you already have.',
        windows: 'Windows: the installer is not code signed yet. If you see "Unknown publisher", choose "More info", then "Run anyway".',
        macos: 'macOS: an unsigned build, so the first launch is blocked. The steps to allow it are in the GitHub readme.',
      },
    },
    footer: {
      tagline: 'A local-first bridge for Amazfit and Zepp data.',
      disclaimer: 'ZeppBridge is an independent open-source project, not affiliated with Zepp Health or Amazfit.',
      source: 'Source',
    },
  },
};
