import type { LandingPack } from '../../composables/useLandingLocale';

const pack: LandingPack = {
  meta: {
    title: 'ZeppBridge · Vom Handgelenk auf deinen Rechner, vom Rechner zur KI',
    description: 'ZeppBridge holt deine Amazfit- und Zepp-Daten aus der Zepp-Cloud auf deinen eigenen Rechner und gibt sie dir als eine Datei für deine KI mit. Kostenlos und quelloffen.',
    ogTitle: 'ZeppBridge · Vom Handgelenk auf den Schreibtisch. Vom Schreibtisch zur KI.',
    ogDescription: 'Herzfrequenz, Schlaf und Training lokal synchronisieren, ansehen und mit einem Klick an die KI deiner Wahl übergeben.',
  },
  copy: {
    nav: { home: 'ZeppBridge Startseite', site: 'Website-Navigation', demo: 'Demo', features: 'Funktionen', ai: 'An die KI', privacy: 'Datenschutz', download: 'Download', github: 'GitHub', language: 'Sprache', toDark: 'Zum dunklen Design', toLight: 'Zum hellen Design' },
    downloads: {
      windows: { label: 'Für Windows laden', hint: 'x64-Installer', msi: 'MSI für verwaltete Installationen' },
      macos: { label: 'Für macOS laden', hint: 'Apple Silicon' },
      linux: { label: 'Linux', previewBadge: 'Experimentell', note: 'deb, rpm, AppImage und Flatpak baut die CI, aber Anmeldung und Schlüsselbund hat noch niemand auf einem echten Linux-Desktop komplett getestet. Probleme? Mach ein Issue auf.' },
      status: { loading: 'Neuestes Installationspaket wird gesucht', ready: 'Klick lädt direkt herunter', fallback: 'Öffnet GitHub Releases, dort wählst du das Paket' },
    },
    sample: 'Beispiel',
    hero: {
      eyebrow: 'Kostenlos · Open Source · Bleibt auf deinem Rechner',
      titleLead: 'Vom Handgelenk auf deinen Rechner.',
      titleAccent: 'Vom Rechner direkt zur KI.',
      lead: 'ZeppBridge holt Herzfrequenz, Schlaf und Training, die deine Amazfit aufgezeichnet hat, aus der Zepp-Cloud auf deinen eigenen Rechner, als Archiv, das du lesen und mitnehmen kannst. Hast du eine Frage, wählst du einen Zeitraum und gibst ihn als eine Datei an eine KI.',
      github: 'Quellcode auf GitHub ansehen',
      pillars: ['Auf deinen Rechner synchronisiert', 'Mit einem Klick an die KI'],
      meta: 'Kostenlos · Windows 10 / 11 · macOS (Apple Silicon) · Linux experimentell',
      devices: 'Diese Amazfit-Geräte kennt es schon',
      toasts: [
        { title: 'Synchronisierung fertig', body: '1.284 neue Einträge, der letzte von heute 07:12' },
        { title: '7 Std. 12 Min. geschlafen', body: '18 Minuten mehr Tiefschlaf als dein 30-Tage-Schnitt' },
        { title: 'Für die KI gepackt', body: 'Schlaf, Herzfrequenz und HRV, letzte 7 Tage, eine .md-Datei' },
        { title: 'Abendlauf, 6,2 km', body: 'Strecke, Pace pro Kilometer und die Herzfrequenzkurve' },
        { title: 'Zwei Stunden ohne Herzfrequenz', body: 'Die Uhr lag nicht am Arm. Die Kurve bleibt leer, nie 0.' },
      ],
      ask: { question: 'Wie habe ich diese Woche geschlafen, verglichen mit letzter?', file: 'ZeppBridge letzte 7 Tage.md' },
      starNudge: { title: 'Dein Download läuft', copy: 'Hilft dir ZeppBridge? Ein Stern auf GitHub hilft anderen Amazfit-Nutzern, es zu finden.', action: 'Stern vergeben', dismiss: 'Später' },
    },
    chapters: { sync: '01 · Auf deinen Rechner', ai: '02 · An die KI' },
    flap: {
      heading: 'Sie hat nie aufgehört mitzuschreiben',
      lead: 'Drei Jahre am Handgelenk ergeben ungefähr so viel. ZeppBridge holt jeden Eintrag zurück und sortiert ihn nach Tagen.',
      tiles: [
        { value: '1.096', label: 'Nächte Schlaf' },
        { value: '742', label: 'Trainings mit Strecke' },
        { value: '1,5M', label: 'Minuten Herzfrequenz' },
        { value: '9,8M', label: 'Schritte' },
      ],
    },
    demo: {
      heading: 'Fühlt sich an wie eine App, nicht wie eine Tabelle',
      lead: 'Wechsle oben den Tab für andere Daten. Dann leg den Schalter um und sieh, wie ein fehlender Messwert aussehen sollte.',
      window: 'ZeppBridge · Übersicht',
      tabs: { heart: 'Herzfrequenz', sleep: 'Schlaf', steps: 'Schritte' },
      nav: ['Übersicht', 'An die KI', 'Trainings', 'Einstellungen'],
      heart: { value: '62', unit: 'bpm', caption: 'Heute im Minutentakt. Die Spitze am Abend ist ein Lauf.' },
      sleep: { value: '7 Std. 12 Min.', caption: 'Eingeschlafen 23:48, aufgewacht 07:00', stages: ['Wach', 'REM', 'Leicht', 'Tief'] },
      steps: { value: '11.406', unit: 'Schritte', caption: 'Schritte pro Stunde. Stunden ohne Gehen bleiben leer.' },
      gap: {
        label: 'Zwei Stunden ohne Uhr',
        honest: 'Leer lassen',
        zero: 'Mit 0 füllen',
        honestNote: 'So zeichnet ZeppBridge: keine Daten heißt keine Daten, die Linie bricht ab.',
        zeroNote: 'So zeichnen es viele Tools: ein Absturz auf null, der wie ein Notfall aussieht.',
      },
    },
    bento: {
      heading: 'Alles, was es braucht. Nichts, was es nicht braucht.',
      lead: 'Jedes Teil läuft auf deinem Rechner, ohne einen Server von uns dazwischen.',
      connect: { title: 'Drei Wege hinein', copy: 'Offizielle Autorisierung zuerst, erweiterte Daten für mehr Metriken, manuelle Eingabe als Rückfall.', rows: ['Offizielle Zepp-Autorisierung', 'Erweiterte Daten', 'Manuelle Eingabe'], states: ['Verbunden', 'Verbunden', 'Bereit'] },
      local: { title: 'Ein Ordner ist alles', copy: 'Die Datenbank liegt im Ordner data neben der App. Kopier ihn und du hast ein vollständiges Backup.' },
      export: { title: 'Nimm es überallhin mit', copy: 'JSON, CSV, GPX und FIT, für jeden Zeitraum, den du wählst.' },
      api: { title: 'Eine Tür für Skripte und KI-Tools', copy: 'Kommandozeile, MCP und eine lokale Nur-Lese-API. Standardmäßig aus, nur 127.0.0.1.', output: ['datenbank   ok', 'letzter sync  heute 07:12', 'nachladen   0 tage offen'] },
      languages: { title: 'Zehn Sprachen', copy: 'Deutsch, Englisch, Chinesisch, Spanisch, Französisch, Niederländisch, zweimal Portugiesisch, Russisch und Hindi.' },
      theme: { title: 'Dunkel zuerst, hell gibt es auch', copy: 'Folgt dem System oder deiner Wahl.', dark: 'Dunkel', light: 'Hell' },
    },
    ai: {
      heading: 'Eine Frage an die KI? Wähl aus, was sie sehen darf.',
      lead: 'Hak ein paar Datenarten an und ZeppBridge packt sie in eine .md-Datei. Zieh sie in die KI, die du sowieso nutzt, und frag wie einen Freund, der alle deine Einträge gelesen hat.',
      pick: 'Diesmal für die KI',
      chips: ['Schlaf', 'Herzfrequenz', 'HRV', 'Trainings', 'Stress', 'Gewicht'],
      picked: '{n} Arten gewählt, letzte 7 Tage',
      file: 'ZeppBridge letzte 7 Tage.md',
      prompt: 'Habe ich diese Woche schlechter geschlafen als letzte? Woran könnte es liegen?',
      answer: 'Etwas schlechter: im Schnitt 38 Minuten weniger, vor allem Tiefschlaf. Dienstag und Donnerstag hattest du abends Training, und in diesen Nächten kam dein Puls langsamer herunter. Probier eine Woche lang, am Nachmittag zu trainieren.',
      note: 'Keine eingebaute KI und kein zusätzliches Konto. Was rausgeht, wie viel und wann, passiert erst, wenn du klickst.',
    },
    privacy: {
      heading: 'Deine Gesundheitsdaten gibt es an zwei Orten',
      lead: 'In der Zepp-Cloud und auf deinem Rechner. Einen dritten gibt es nicht.',
      nodes: { watch: 'Uhr', cloud: 'Zepp-Cloud', computer: 'Dein Rechner', server: 'ZeppBridge-Server', none: 'gibt es nicht' },
      points: [
        { title: 'Token im Systemtresor', copy: 'In der Windows-Anmeldeinformationsverwaltung oder im macOS-Schlüsselbund, nie im Datenordner.' },
        { title: 'Keine Telemetrie', copy: 'Kein Nutzungstracking, keine Gesundheitsdaten werden gesammelt.' },
        { title: 'Klare Herkunft', copy: 'Jeder Eintrag weiß, ob er aus der offiziellen Autorisierung oder den erweiterten Daten stammt.' },
      ],
    },
    connect: {
      heading: 'Drei Wege zum Verbinden. Nimm den bequemsten.',
      lead: 'Starte mit der offiziellen Autorisierung. Nimm die erweiterten Daten dazu, wenn du mehr Metriken willst.',
      recommended: 'Empfohlen',
      paths: [
        { title: 'Offizielle Zepp-Autorisierung', copy: 'Melde dich in deinem gewohnten Browser bei Zepp an und stimm zu.', detail: 'Google-, Xiaomi- und Apple-Konten funktionieren. Schlaf, Herzfrequenz, Schritte, Trainings, PAI und Gewicht werden synchronisiert.' },
        { title: 'Erweiterte Daten', copy: 'Ergänzt HRV, Blutsauerstoff, Stress und Bereitschaft, die die offizielle API nicht bietet.', detail: 'Anmeldung mit E-Mail oder Telefonnummer. Der Token liegt nur in deinem Systemtresor.' },
        { title: 'Manuelle Eingabe', copy: 'Der Rückfall, wenn beides andere nicht geht.', detail: 'Du fügst selbst einen Token ein. Gedacht für Leute, die die API kennen.' },
      ],
      note: 'Was synchronisiert wird, hängt davon ab, was dein Konto in der Zepp-Cloud hat. Welche Metriken du siehst, hängt von deinem Gerät und deiner Verbindungsart ab.',
    },
    final: {
      heading: 'Installier es und sieh, woran sich deine Uhr erinnert',
      lead: 'Kostenlos, Open Source, ohne Registrierung.',
      facts: {
        channel: 'Stabiler Kanal, Installer von GitHub Releases',
        systems: 'Windows 10 / 11 (x64) und macOS (Apple Silicon). Linux ist experimentell.',
        ai: 'Kein zusätzliches Konto nötig. Für KI-Fragen nimmst du die, die du schon hast.',
        windows: 'Windows: Der Installer ist noch nicht signiert. Siehst du "Unbekannter Herausgeber", wähl "Weitere Informationen" und dann "Trotzdem ausführen".',
        macos: 'macOS: ein unsignierter Build, der erste Start wird blockiert. Wie du ihn erlaubst, steht im GitHub-Readme.',
      },
    },
    footer: {
      tagline: 'Eine lokale Brücke für Amazfit- und Zepp-Daten.',
      disclaimer: 'ZeppBridge ist ein unabhängiges Open-Source-Projekt und nicht mit Zepp Health oder Amazfit verbunden.',
      source: 'Quellcode',
    },
  },
};

export default pack;
