import type { LandingPack } from '../../composables/useLandingLocale';

const pack: LandingPack = {
  meta: {
    title: 'ZeppBridge · De tu muñeca a tu computadora, de tu computadora a la IA',
    description: 'ZeppBridge trae tus datos de Amazfit y Zepp desde la nube de Zepp a tu propia computadora y te los deja listos en un archivo para tu IA. Gratis y de código abierto.',
    ogTitle: 'ZeppBridge · De la muñeca al escritorio. Del escritorio a la IA.',
    ogDescription: 'Sincroniza y revisa en local tu frecuencia cardiaca, sueño y entrenamientos, y entrégalos con un clic a la IA que ya usas.',
  },
  copy: {
    nav: { home: 'Inicio de ZeppBridge', site: 'Navegación del sitio', demo: 'Demostración', features: 'Funciones', ai: 'Para la IA', privacy: 'Privacidad', download: 'Descargar', github: 'GitHub', language: 'Idioma', toDark: 'Cambiar a oscuro', toLight: 'Cambiar a claro' },
    downloads: {
      windows: { label: 'Descargar para Windows', hint: 'Instalador x64', msi: 'MSI para instalaciones gestionadas' },
      macos: { label: 'Descargar para macOS', hint: 'Apple Silicon' },
      linux: { label: 'Linux', previewBadge: 'Experimental', note: 'La CI genera deb, rpm, AppImage y Flatpak, pero nadie ha probado todavía el inicio de sesión y el llavero de principio a fin en un escritorio Linux real. ¿Algún problema? Abre un issue.' },
      status: { loading: 'Buscando el instalador más reciente', ready: 'Haz clic para descargar directo', fallback: 'Se abre GitHub Releases, ahí eliges el instalador' },
    },
    sample: 'Ejemplo',
    hero: {
      eyebrow: 'Gratis · Código abierto · Se queda en tu equipo',
      titleLead: 'De tu muñeca a tu computadora.',
      titleAccent: 'De tu computadora a la IA.',
      lead: 'ZeppBridge trae desde la nube de Zepp la frecuencia cardiaca, el sueño y los entrenamientos que registró tu Amazfit, y los guarda en tu computadora como un archivo que puedes leer y llevar contigo. Cuando tengas una pregunta, eliges un rango y se lo das a una IA en un solo archivo.',
      github: 'Ver el código en GitHub',
      pillars: ['Sincronizado a tu computadora', 'Entregado a tu IA con un clic'],
      meta: 'Gratis · Windows 10 / 11 · macOS (Apple Silicon) · Linux experimental',
      devices: 'Dispositivos Amazfit que ya reconoce',
      toasts: [
        { title: 'Sincronización lista', body: '1284 registros nuevos, el último de hoy a las 07:12' },
        { title: 'Dormiste 7 h 12 min', body: '18 minutos más de sueño profundo que tu promedio de 30 días' },
        { title: 'Listo para tu IA', body: 'Sueño, frecuencia cardiaca y HRV, últimos 7 días, un archivo .md' },
        { title: 'Carrera de la tarde, 6,2 km', body: 'Ruta, ritmo por kilómetro y la curva de frecuencia cardiaca' },
        { title: 'Dos horas sin frecuencia cardiaca', body: 'El reloj no estaba en tu muñeca. La gráfica queda vacía, nunca en 0.' },
      ],
      ask: { question: '¿Cómo dormí esta semana comparado con la anterior?', file: 'ZeppBridge últimos 7 días.md' },
      starNudge: { title: 'Tu descarga comenzó', copy: 'Si ZeppBridge te sirve, una estrella en GitHub ayuda a que otras personas con Amazfit lo encuentren.', action: 'Dar una estrella', dismiss: 'Más tarde' },
    },
    chapters: { sync: '01 · A tu computadora', ai: '02 · A tu IA' },
    flap: {
      heading: 'Nunca dejó de tomar nota',
      lead: 'Tres años en la muñeca suman más o menos esto. ZeppBridge trae de vuelta cada registro y lo ordena por día.',
      tiles: [
        { value: '1096', label: 'noches de sueño' },
        { value: '742', label: 'entrenamientos con ruta' },
        { value: '1,5M', label: 'minutos de frecuencia cardiaca' },
        { value: '9,8M', label: 'pasos' },
      ],
    },
    demo: {
      heading: 'Se siente como una app, no como una hoja de cálculo',
      lead: 'Cambia de pestaña para ver otro tipo de datos. Luego mueve el interruptor y mira cómo debería verse un dato que falta.',
      window: 'ZeppBridge · Resumen',
      tabs: { heart: 'Frecuencia', sleep: 'Sueño', steps: 'Pasos' },
      nav: ['Resumen', 'Para la IA', 'Entrenamientos', 'Ajustes'],
      heart: { value: '62', unit: 'lpm', caption: 'Minuto a minuto hoy. El pico de la tarde es una carrera.' },
      sleep: { value: '7 h 12 min', caption: 'Te dormiste a las 23:48 y despertaste a las 07:00', stages: ['Despierto', 'REM', 'Ligero', 'Profundo'] },
      steps: { value: '11 406', unit: 'pasos', caption: 'Pasos por hora. Las horas sin caminar quedan vacías.' },
      gap: {
        label: 'Dos horas sin el reloj',
        honest: 'Dejar vacío',
        zero: 'Rellenar con 0',
        honestNote: 'Así lo dibuja ZeppBridge: sin datos no hay datos, y la línea se corta.',
        zeroNote: 'Así lo dibujan muchas herramientas: una caída a cero que parece una emergencia.',
      },
    },
    bento: {
      heading: 'Todo lo que necesita. Nada que no.',
      lead: 'Cada pieza corre en tu equipo, sin ningún servidor nuestro de por medio.',
      connect: { title: 'Tres formas de entrar', copy: 'Primero la autorización oficial, datos avanzados para más métricas y la entrada manual como respaldo.', rows: ['Autorización oficial de Zepp', 'Datos avanzados', 'Entrada manual'], states: ['Conectado', 'Conectado', 'En espera'] },
      local: { title: 'Una carpeta lo es todo', copy: 'La base de datos vive en la carpeta data junto a la app. Cópiala y tienes un respaldo completo.' },
      export: { title: 'Llévalo a donde quieras', copy: 'JSON, CSV, GPX y FIT, para el rango que elijas.' },
      api: { title: 'Una puerta para scripts y herramientas de IA', copy: 'Línea de comandos, MCP y una API local de solo lectura. Apagada por defecto, solo en 127.0.0.1.', output: ['base de datos   ok', 'última sync     hoy 07:12', 'por recuperar   0 días'] },
      languages: { title: 'Diez idiomas', copy: 'Español, inglés, chino, alemán, francés, neerlandés, dos variantes de portugués, ruso e hindi.' },
      theme: { title: 'Oscuro primero, también claro', copy: 'Sigue al sistema o elige tú.', dark: 'Oscuro', light: 'Claro' },
    },
    ai: {
      heading: '¿Le vas a preguntar a una IA? Elige qué puede ver.',
      lead: 'Marca algunos tipos de datos y ZeppBridge los empaqueta en un archivo .md. Suéltalo en la IA que ya usas y pregunta como le preguntarías a alguien que leyó todos tus registros.',
      pick: 'Esta vez para la IA',
      chips: ['Sueño', 'Frecuencia', 'HRV', 'Entrenos', 'Estrés', 'Peso'],
      picked: '{n} tipos elegidos, últimos 7 días',
      file: 'ZeppBridge últimos 7 días.md',
      prompt: '¿Dormí peor esta semana que la anterior? ¿Qué podría explicarlo?',
      answer: 'Un poco peor: 38 minutos menos en promedio, sobre todo de sueño profundo. El martes y el jueves entrenaste de noche, y esas noches tu pulso tardó más en bajar. Prueba una semana entrenando por la tarde.',
      note: 'Sin IA integrada y sin otra cuenta. Qué se envía, cuánto y cuándo solo pasa cuando tú haces clic.',
    },
    privacy: {
      heading: 'Tus datos de salud viven en dos lugares',
      lead: 'La nube de Zepp y tu propia computadora. No hay un tercero.',
      nodes: { watch: 'Reloj', cloud: 'Nube de Zepp', computer: 'Tu computadora', server: 'Servidor de ZeppBridge', none: 'no existe' },
      points: [
        { title: 'Tokens en la bóveda del sistema', copy: 'Se guardan en el Administrador de credenciales de Windows o en el Llavero de macOS, nunca en la carpeta de datos.' },
        { title: 'Sin telemetría', copy: 'No medimos cómo la usas ni recopilamos datos de salud.' },
        { title: 'Origen claro', copy: 'Cada registro sabe si vino de la autorización oficial o de los datos avanzados.' },
      ],
    },
    connect: {
      heading: 'Tres formas de conectarte. Elige la más cómoda.',
      lead: 'Empieza con la autorización oficial. Agrega datos avanzados cuando quieras más métricas.',
      recommended: 'Recomendado',
      paths: [
        { title: 'Autorización oficial de Zepp', copy: 'Inicia sesión en Zepp desde tu navegador de siempre y acepta.', detail: 'Funcionan cuentas de Google, Xiaomi y Apple. Se sincronizan sueño, frecuencia cardiaca, pasos, entrenamientos, PAI y peso.' },
        { title: 'Datos avanzados', copy: 'Agrega HRV, oxígeno en sangre, estrés y disposición, que la API oficial no ofrece.', detail: 'Inicias sesión con correo o teléfono. El token solo vive en la bóveda de tu sistema.' },
        { title: 'Entrada manual', copy: 'El respaldo cuando las otras dos no funcionan.', detail: 'Pegas tú un token. Pensado para quien conoce la API.' },
      ],
      note: 'Lo que se sincroniza depende de lo que tu cuenta guarda en la nube de Zepp. Las métricas que ves dependen de tu dispositivo y de cómo te conectas.',
    },
    final: {
      heading: 'Instálalo y mira lo que tu reloj recuerda',
      lead: 'Gratis, de código abierto, sin registro.',
      facts: {
        channel: 'Canal estable, instaladores desde GitHub Releases',
        systems: 'Windows 10 / 11 (x64) y macOS (Apple Silicon). Linux es experimental.',
        ai: 'No necesitas otra cuenta. Para preguntar a una IA usas la que ya tienes.',
        windows: 'Windows: el instalador aún no está firmado. Si ves "Editor desconocido", elige "Más información" y luego "Ejecutar de todas formas".',
        macos: 'macOS: una compilación sin firmar, así que el primer arranque se bloquea. Los pasos para permitirlo están en el readme de GitHub.',
      },
    },
    footer: {
      tagline: 'Un puente local para los datos de Amazfit y Zepp.',
      disclaimer: 'ZeppBridge es un proyecto independiente de código abierto, sin relación con Zepp Health ni con Amazfit.',
      source: 'Código fuente',
    },
  },
};

export default pack;
