import type { LandingPack } from '../../composables/useLandingLocale';

const pack: LandingPack = {
  meta: {
    title: 'ZeppBridge · Du poignet à ton ordinateur, de ton ordinateur à l’IA',
    description: 'ZeppBridge ramène tes données Amazfit et Zepp du cloud Zepp vers ton propre ordinateur et te les prépare en un seul fichier pour ton IA. Gratuit et open source.',
    ogTitle: 'ZeppBridge · Du poignet au bureau. Du bureau à l’IA.',
    ogDescription: 'Synchronise et consulte en local ta fréquence cardiaque, ton sommeil et tes séances, puis confie-les en un clic à l’IA que tu utilises déjà.',
  },
  copy: {
    nav: { home: 'Accueil ZeppBridge', site: 'Navigation du site', demo: 'Démo', features: 'Fonctions', ai: 'Pour l’IA', privacy: 'Confidentialité', download: 'Télécharger', github: 'GitHub', language: 'Langue', toDark: 'Passer en sombre', toLight: 'Passer en clair' },
    downloads: {
      windows: { label: 'Télécharger pour Windows', hint: 'Installeur x64', msi: 'MSI pour les installations gérées' },
      macos: { label: 'Télécharger pour macOS', hint: 'Apple Silicon' },
      linux: { label: 'Linux', previewBadge: 'Expérimental', note: 'La CI produit deb, rpm, AppImage et Flatpak, mais personne n’a encore testé de bout en bout la connexion et le trousseau sur un vrai bureau Linux. Un souci ? Ouvre une issue.' },
      status: { loading: 'Recherche du dernier installeur', ready: 'Clique pour télécharger directement', fallback: 'Ouvre GitHub Releases, où tu choisis l’installeur' },
    },
    sample: 'Exemple',
    hero: {
      eyebrow: 'Gratuit · Open source · Reste sur ta machine',
      titleLead: 'Du poignet à ton ordinateur.',
      titleAccent: 'De ton ordinateur à l’IA.',
      lead: 'ZeppBridge ramène du cloud Zepp la fréquence cardiaque, le sommeil et les séances enregistrés par ta montre Amazfit, et les garde sur ton ordinateur comme une archive que tu peux lire et emporter. Quand tu as une question, choisis une période et confie-la à une IA en un seul fichier.',
      github: 'Lire le code sur GitHub',
      pillars: ['Synchronisé sur ton ordinateur', 'Confié à ton IA en un clic'],
      meta: 'Gratuit · Windows 10 / 11 · macOS (Apple Silicon) · Linux expérimental',
      devices: 'Les montres Amazfit qu’il connaît déjà',
      toasts: [
        { title: 'Synchronisation terminée', body: '1 284 nouveaux relevés, le dernier ce matin à 07:12' },
        { title: 'Nuit de 7 h 12', body: '18 minutes de sommeil profond de plus que ta moyenne sur 30 jours' },
        { title: 'Prêt pour ton IA', body: 'Sommeil, fréquence cardiaque et VFC, 7 derniers jours, un fichier .md' },
        { title: 'Course du soir, 6,2 km', body: 'Tracé, allure au kilomètre et courbe de fréquence cardiaque' },
        { title: 'Deux heures sans fréquence cardiaque', body: 'La montre n’était pas au poignet. Le graphique reste vide, jamais à 0.' },
      ],
      ask: { question: 'Comment ai-je dormi cette semaine par rapport à la précédente ?', file: 'ZeppBridge 7 derniers jours.md' },
      starNudge: { title: 'Ton téléchargement a commencé', copy: 'Si ZeppBridge t’aide, une étoile sur GitHub aide d’autres personnes équipées d’Amazfit à le trouver.', action: 'Mettre une étoile', dismiss: 'Plus tard' },
    },
    chapters: { sync: '01 · Sur ton ordinateur', ai: '02 · Pour ton IA' },
    flap: {
      heading: 'Elle n’a jamais cessé de prendre des notes',
      lead: 'Trois ans au poignet, ça donne à peu près ceci. ZeppBridge récupère chaque relevé et les range jour par jour.',
      tiles: [
        { value: '1 096', label: 'nuits de sommeil' },
        { value: '742', label: 'séances avec tracé' },
        { value: '1,5M', label: 'minutes de fréquence cardiaque' },
        { value: '9,8M', label: 'pas' },
      ],
    },
    demo: {
      heading: 'On dirait une app, pas un tableur',
      lead: 'Change d’onglet pour voir d’autres données. Puis bascule l’interrupteur et regarde comment une mesure manquante devrait s’afficher.',
      window: 'ZeppBridge · Aperçu',
      tabs: { heart: 'Cardio', sleep: 'Sommeil', steps: 'Pas' },
      nav: ['Aperçu', 'Pour l’IA', 'Séances', 'Réglages'],
      heart: { value: '62', unit: 'bpm', caption: 'Minute par minute aujourd’hui. Le pic du soir, c’est une course.' },
      sleep: { value: '7 h 12', caption: 'Endormi à 23:48, réveillé à 07:00', stages: ['Éveil', 'REM', 'Léger', 'Profond'] },
      steps: { value: '11 406', unit: 'pas', caption: 'Pas par heure. Les heures sans marche restent vides.' },
      gap: {
        label: 'Deux heures sans la montre',
        honest: 'Laisser vide',
        zero: 'Remplir avec 0',
        honestNote: 'Comme le dessine ZeppBridge : pas de données, c’est pas de données, la ligne s’interrompt.',
        zeroNote: 'Comme le dessinent bien des outils : une chute à zéro qui ressemble à une urgence.',
      },
    },
    bento: {
      heading: 'Tout ce qu’il faut. Rien de superflu.',
      lead: 'Chaque brique tourne sur ta machine, sans aucun serveur à nous au milieu.',
      connect: { title: 'Trois façons d’entrer', copy: 'L’autorisation officielle d’abord, les données avancées pour plus de mesures, la saisie manuelle en secours.', rows: ['Autorisation officielle Zepp', 'Données avancées', 'Saisie manuelle'], states: ['Connecté', 'Connecté', 'En réserve'] },
      local: { title: 'Un dossier, et c’est tout', copy: 'La base de données vit dans le dossier data à côté de l’app. Copie-le et tu as une sauvegarde complète.' },
      export: { title: 'Emporte-le où tu veux', copy: 'JSON, CSV, GPX et FIT, sur la période de ton choix.' },
      api: { title: 'Une porte pour les scripts et les outils d’IA', copy: 'Ligne de commande, MCP et une API locale en lecture seule. Désactivée par défaut, uniquement sur 127.0.0.1.', output: ['base de données   ok', 'dernière synchro  aujourd’hui 07:12', 'à rattraper       0 jour'] },
      languages: { title: 'Dix langues', copy: 'Français, anglais, chinois, espagnol, allemand, néerlandais, deux variantes de portugais, russe et hindi.' },
      theme: { title: 'Sombre d’abord, clair aussi', copy: 'Suit le système, ou ton choix.', dark: 'Sombre', light: 'Clair' },
    },
    ai: {
      heading: 'Une question pour une IA ? Choisis ce qu’elle peut voir.',
      lead: 'Coche quelques types de données et ZeppBridge les rassemble dans un fichier .md. Dépose-le dans l’IA que tu utilises déjà et pose ta question comme à un ami qui aurait lu tous tes relevés.',
      pick: 'Cette fois pour l’IA',
      chips: ['Sommeil', 'Cardio', 'VFC', 'Séances', 'Stress', 'Poids'],
      picked: '{n} types choisis, 7 derniers jours',
      file: 'ZeppBridge 7 derniers jours.md',
      prompt: 'Ai-je moins bien dormi cette semaine que la précédente ? Pourquoi, à ton avis ?',
      answer: 'Un peu moins bien : 38 minutes de moins en moyenne, surtout en sommeil profond. Mardi et jeudi, tu t’es entraîné le soir, et ces nuits-là ton cœur a mis plus de temps à ralentir. Essaie une semaine en t’entraînant l’après-midi.',
      note: 'Pas d’IA intégrée, pas de compte en plus. Ce qui part, combien et quand, ça n’arrive que quand tu cliques.',
    },
    privacy: {
      heading: 'Tes données de santé vivent à deux endroits',
      lead: 'Le cloud Zepp et ton propre ordinateur. Il n’y en a pas de troisième.',
      nodes: { watch: 'Montre', cloud: 'Cloud Zepp', computer: 'Ton ordinateur', server: 'Serveur ZeppBridge', none: 'n’existe pas' },
      points: [
        { title: 'Jetons dans le coffre du système', copy: 'Rangés dans le Gestionnaire d’identification de Windows ou le trousseau macOS, jamais dans le dossier de données.' },
        { title: 'Aucune télémétrie', copy: 'Aucun suivi d’usage, aucune donnée de santé collectée.' },
        { title: 'Origine claire', copy: 'Chaque relevé sait s’il vient de l’autorisation officielle ou des données avancées.' },
      ],
    },
    connect: {
      heading: 'Trois façons de te connecter. Prends la plus simple.',
      lead: 'Commence par l’autorisation officielle. Ajoute les données avancées quand tu veux plus de mesures.',
      recommended: 'Recommandé',
      paths: [
        { title: 'Autorisation officielle Zepp', copy: 'Connecte-toi à Zepp dans ton navigateur habituel et accepte.', detail: 'Les comptes Google, Xiaomi et Apple fonctionnent. Sommeil, fréquence cardiaque, pas, séances, PAI et poids se synchronisent.' },
        { title: 'Données avancées', copy: 'Ajoute la VFC, l’oxygène sanguin, le stress et la disponibilité, que l’API officielle ne propose pas.', detail: 'Connexion par e-mail ou téléphone. Le jeton reste uniquement dans le coffre de ton système.' },
        { title: 'Saisie manuelle', copy: 'Le recours quand les deux autres ne marchent pas.', detail: 'Tu colles toi-même un jeton. Pour celles et ceux qui connaissent l’API.' },
      ],
      note: 'Ce qui se synchronise dépend de ce que ton compte contient dans le cloud Zepp. Les mesures que tu vois dépendent de ton appareil et de ta façon de te connecter.',
    },
    final: {
      heading: 'Installe-le et découvre ce dont ta montre se souvient',
      lead: 'Gratuit, open source, sans inscription.',
      facts: {
        channel: 'Canal stable, installeurs sur GitHub Releases',
        systems: 'Windows 10 / 11 (x64) et macOS (Apple Silicon). Linux est expérimental.',
        ai: 'Aucun compte en plus. Pour les questions à une IA, tu utilises celle que tu as déjà.',
        windows: 'Windows : l’installeur n’est pas encore signé. Si tu vois "Éditeur inconnu", choisis "Informations complémentaires" puis "Exécuter quand même".',
        macos: 'macOS : une version non signée, le premier lancement est donc bloqué. Les étapes pour l’autoriser sont dans le readme GitHub.',
      },
    },
    footer: {
      tagline: 'Un pont local pour les données Amazfit et Zepp.',
      disclaimer: 'ZeppBridge est un projet open source indépendant, sans lien avec Zepp Health ni Amazfit.',
      source: 'Code source',
    },
  },
};

export default pack;
