import type { LandingLocale } from '../../composables/useLandingLocale';

export interface JourneyLine { id: string; title: string; text: string }
export interface JourneyTurn { prompt: string; answer: string }
export interface JourneyCopy {
  title: [string, string]; lead: string;
  nav: { product: string; motion: string; try: string; download: string; menu: string };
  groups: { records: string; ai: string; connect: string };
  links: { overview: string; sleep: string; workouts: string; ask: string; plan: string; arrange: string; mcp: string; api: string; settings: string };
  themes: [string, string, string];
  motionTitle: string; motionLead: string; motions: JourneyLine[];
  recordsTitle: string; records: JourneyLine[];
  aiTitle: string; aiLead: string; you: string; reply: string; turns: JourneyTurn[]; beats: JourneyLine[];
  settingsTitle: string; settingsLead: string; settings: JourneyLine[];
  demoTitle: string; demoLead: string; demoStart: string; demoReset: string;
  demoTabs: [string, string, string, string, string];
  back: string;
  downloadTitle: string; downloadLead: string; downloadPending: string; install: string;
  system: string;
}

const zh: JourneyCopy = {
  title: ['睡眠、运动和恢复', '留在这台电脑上。'],
  lead: '从 Zepp 同步到本机。概览、睡眠分期、运动对比和训练计划在同一处查看。',
  nav: { product: '产品', motion: '动效', try: '亲自试试', download: '下载', menu: '打开菜单' },
  groups: { records: '记录', ai: '交给 AI', connect: '接出去' },
  links: { overview: '概览', sleep: '睡眠与恢复', workouts: '运动', ask: '问答', plan: '训练计划', arrange: '理牌', mcp: 'MCP', api: '本机 API', settings: '高级设置' },
  themes: ['深色', '浅色', '系统'],
  motionTitle: '动效',
  motionLead: '从一次点按到松手回弹。五段操作，自动依次演示。',
  motions: [
    { id: 'glass', title: '底部玻璃', text: '按住、拖动、松手。透镜跟随指针，边缘折射掠过背景。' },
    { id: 'poker', title: '挑日子与翻牌', text: '7 天、1 个月、6 个月，再逐层返回。最后点空白，整副牌归位。' },
    { id: 'seasons', title: '四季卡', text: '从空白添加四个固定项，回首页查看，再一一移除。' },
    { id: 'notes', title: '注释与回弹', text: '点开睡眠时长的说明，再拖起卡牌，看聚焦与松手回弹。' },
    { id: 'box', title: '收集箱', text: '收集箱展开，条目进去，再合上。' },
  ],
  recordsTitle: '记录',
  records: [
    { id: 'overview', title: '概览', text: '静息心率、心率变异性、睡眠评分和步数在同一页。' },
    { id: 'sleep', title: '睡眠', text: '每晚的时长、评分和分期。没有测到的时段留空。' },
    { id: 'workouts', title: '运动', text: '这次和自己以往相近距离的对比，加上心率、配速和轨迹。' },
  ],
  aiTitle: '交给 AI',
  aiLead: '带上记录问问题，继续追问，再把计划接回来。一段完整的示例对话，约 45 秒。',
  you: '你', reply: '回复',
  turns: [
    { prompt: '用这份睡眠和运动记录排接下来一周。没有测到的写成未提供，保留休息日。', answer: '我会把这份示例记录里的睡眠和运动分开整理。没有采样的日期保留为“未提供”，不推测原因，也不把缺失写成零。\n\n这一周先安排轻松跑、恢复骑行、节奏跑和间歇，再留出休息日。每次训练都拆成可查看的步骤，热身与放松单独保留。你可以继续调整时长；这仍是一份待确认的草稿。' },
    { prompt: '第一场轻松跑改成 40 分钟，保留热身和放松。', answer: '已把第一场轻松跑调整为 40 分钟：6 分钟热身、28 分钟轻松跑、6 分钟放松。三段会分别显示在计划卡里。\n\n其余日期和项目保持原来的安排，休息日也保留。接下来可以把草稿整理成 Plan，再回到 ZeppBridge 逐日查看、交换日期或修改细节。' },
  ],
  beats: [
    { id: 'plan', title: '一周计划', text: '七天里每天是训练还是休息。' },
    { id: 'arrange', title: '理牌和删除', text: '拖动可以交换两天，也可以删掉一张。' },
    { id: 'prompt', title: '自定义问题', text: '发送前可以改这段话。' },
    { id: 'types', title: '日期和运动类型', text: '先勾日期范围，再勾要带上的运动类型。' },
  ],
  settingsTitle: '接出去与高级设置',
  settingsLead: '这些都在同一块里，不另开页面。',
  settings: [
    { id: 'mcp', title: 'MCP', text: '外部工具通过本机只读 MCP 读取档案。' },
    { id: 'api', title: '本机 API', text: '只绑定 127.0.0.1，只读。' },
    { id: 'timezone', title: '时区', text: '同一条记录按所选时区显示日期。' },
    { id: 'units', title: '单位', text: '距离和配速按所选单位显示。' },
    { id: 'time', title: '时间', text: '时间的显示格式在这里改。' },
    { id: 'year', title: '年份', text: '按年份查看档案。' },
    { id: 'range', title: '范围', text: '选择要看的起止日期。' },
    { id: 'events', title: '生活事件', text: '把一件事记在某一天，和睡眠、运动放在一起。' },
  ],
  demoTitle: '现在可以自己点。',
  demoLead: '一年的虚构记录。改动只留在这次示例里。',
  demoStart: '点击开始', demoReset: '重置示例',
  demoTabs: ['本地档案', '睡眠记录', '运动与训练', '交给 AI', '计划'],
  back: '返回介绍',
  downloadTitle: '安装到这台电脑',
  downloadLead: '免费开源。v3 正式安装包尚未发布。',
  downloadPending: 'v3 正式安装包尚未发布',
  install: 'Windows 运行安装包。macOS 拖进应用程序。Linux 选对应的包。',
  system: '跟随系统',
};

const en: JourneyCopy = {
  title: ['Sleep, workouts, recovery', 'on this computer.'],
  lead: 'Sync from Zepp to this machine. Overview, sleep stages, workout comparison and the training plan sit in one place.',
  nav: { product: 'Product', motion: 'Motion', try: 'Try it', download: 'Download', menu: 'Open menu' },
  groups: { records: 'Records', ai: 'Send to AI', connect: 'Connect' },
  links: { overview: 'Overview', sleep: 'Sleep and recovery', workouts: 'Workouts', ask: 'Exchange', plan: 'Training plan', arrange: 'Arrange cards', mcp: 'MCP', api: 'Local API', settings: 'Advanced' },
  themes: ['Dark', 'Light', 'System'],
  motionTitle: 'Motion',
  motionLead: 'From the first press to the last spring. Five interactions, played in sequence.',
  motions: [
    { id: 'glass', title: 'Bottom glass', text: 'Press, drag and release. The lens follows your pointer, refracting its background.' },
    { id: 'poker', title: 'Pick days and flip', text: 'Seven days, one month, six months, and back. Tap the empty space to gather the deck.' },
    { id: 'seasons', title: 'Four pinned cards', text: 'Add four metrics to an empty home, view them, then remove them one by one.' },
    { id: 'notes', title: 'Notes and spring', text: 'Open a sleep-duration note, then lift a card and watch it settle when released.' },
    { id: 'box', title: 'Collection box', text: 'The box opens, takes an item, then closes.' },
  ],
  recordsTitle: 'Records',
  records: [
    { id: 'overview', title: 'Overview', text: 'Resting heart rate, HRV, sleep score and steps on one page.' },
    { id: 'sleep', title: 'Sleep', text: 'Duration, score and stages for each night. Unmeasured time stays empty.' },
    { id: 'workouts', title: 'Workouts', text: 'This session against your own similar distances, with heart rate, pace and the route.' },
  ],
  aiTitle: 'Send to AI',
  aiLead: 'Ask with your records, refine the answer, and bring the plan back. A complete sample conversation in about 45 seconds.',
  you: 'You', reply: 'Reply',
  turns: [
    { prompt: 'Plan the coming week with these sleep and workout records. Mark missing measurements as not provided and keep rest days.', answer: 'I will organise the sleep and workouts in this sample separately. Days without measurements stay “not provided”; missing data is never treated as zero.\n\nThe draft combines an easy run, recovery ride, tempo run and intervals with rest days. Each session has individual steps, including its warm-up and cooldown. You can refine the durations before bringing this draft back for review.' },
    { prompt: 'Make the first easy run 40 minutes, keeping the warm-up and cooldown.', answer: 'The first easy run is now 40 minutes: a 6-minute warm-up, 28 minutes of easy running and a 6-minute cooldown. The plan card will show these as three separate steps.\n\nThe other sessions and rest days stay as planned. Next, I can package the draft as a Plan so you can inspect each day, swap dates and make further changes in ZeppBridge.' },
  ],
  beats: [
    { id: 'plan', title: 'Week plan', text: 'Seven days, each one a workout or a rest day.' },
    { id: 'arrange', title: 'Arrange and delete', text: 'Drag to swap two days, or delete a card.' },
    { id: 'prompt', title: 'Custom prompt', text: 'You can edit the question before it is sent.' },
    { id: 'types', title: 'Dates and sport types', text: 'Check a date range, then the workout types to include.' },
  ],
  settingsTitle: 'Connections and advanced settings',
  settingsLead: 'These sit on one board. None of them has its own page.',
  settings: [
    { id: 'mcp', title: 'MCP', text: 'Other tools read the archive through the local read-only MCP.' },
    { id: 'api', title: 'Local API', text: 'Bound to 127.0.0.1. Read only.' },
    { id: 'timezone', title: 'Time zone', text: 'The same record shows its date in the zone you pick.' },
    { id: 'units', title: 'Units', text: 'Distance and pace use the units you pick.' },
    { id: 'time', title: 'Time', text: 'The clock format is changed here.' },
    { id: 'year', title: 'Year', text: 'Open the archive by year.' },
    { id: 'range', title: 'Range', text: 'Pick the start and end dates to view.' },
    { id: 'events', title: 'Life events', text: 'Write an event on a day and read it next to sleep and workouts.' },
  ],
  demoTitle: 'Click through it yourself.',
  demoLead: 'A year of fictional records. Changes stay in this sample.',
  demoStart: 'Click to start', demoReset: 'Reset sample',
  demoTabs: ['Archive', 'Sleep', 'Workouts', 'Send to AI', 'Plan'],
  back: 'Back to the intro',
  downloadTitle: 'Install on this computer',
  downloadLead: 'Free and open source. The v3 release is not available yet.',
  downloadPending: 'The v3 release is not available yet',
  install: 'Run the Windows installer. Drag the macOS app into Applications. Pick a package for Linux.',
  system: 'System',
};

function pack(partial: Pick<JourneyCopy, 'title' | 'lead' | 'nav' | 'groups' | 'links' | 'themes' | 'motionTitle' | 'motionLead' | 'motions' | 'recordsTitle' | 'records' | 'aiTitle' | 'aiLead' | 'you' | 'reply' | 'turns' | 'beats' | 'settingsTitle' | 'settingsLead' | 'settings' | 'demoTitle' | 'demoLead' | 'demoStart' | 'demoReset' | 'demoTabs' | 'back' | 'downloadTitle' | 'downloadLead' | 'downloadPending' | 'install' | 'system'>): JourneyCopy {
  return partial;
}

export const JOURNEY: Record<LandingLocale, JourneyCopy> = {
  zh, en,
  es: pack({
    title: ['Sueño, entrenos y recuperación', 'en este ordenador.'],
    lead: 'Sincroniza desde Zepp a este equipo. Resumen, fases del sueño, comparación de entrenos y plan quedan juntos.',
    nav: { product: 'Producto', motion: 'Movimiento', try: 'Probar', download: 'Descargar', menu: 'Abrir menú' },
    groups: { records: 'Registros', ai: 'Enviar a la IA', connect: 'Salidas' },
    links: { overview: 'Resumen', sleep: 'Sueño y recuperación', workouts: 'Entrenos', ask: 'Intercambio', plan: 'Plan', arrange: 'Ordenar cartas', mcp: 'MCP', api: 'API local', settings: 'Ajustes' },
    themes: ['Oscuro', 'Claro', 'Sistema'],
    motionTitle: 'Movimiento', motionLead: "Cinco interacciones completas, reproducidas en secuencia.",
    motions: [
      { id: "glass", title: "Vidrio inferior", text: "Pulsa, arrastra y suelta. La lente sigue el puntero y refracta el fondo." },
      { id: "poker", title: "Elegir días y voltear", text: "7 días, 1 mes, 6 meses y vuelta. Pulsa el espacio vacío para recoger las cartas." },
      { id: "seasons", title: "Cuatro métricas fijas", text: "Añade cuatro métricas, míralas en el inicio y retíralas una a una." },
      { id: "notes", title: "Notas y rebote", text: "Abre la nota de duración del sueño, arrastra una carta y suéltala." },
      { id: "box", title: "Caja", text: "La caja se abre, recibe una carta y se cierra." },
    ],
    recordsTitle: 'Registros',
    records: [
      { id: 'overview', title: 'Resumen', text: 'Pulso en reposo, VFC, puntuación de sueño y pasos en la misma página.' },
      { id: 'sleep', title: 'Sueño', text: 'Duración, puntuación y fases de cada noche. Lo no medido queda vacío.' },
      { id: 'workouts', title: 'Entrenos', text: 'Esta sesión frente a distancias parecidas tuyas, con pulso, ritmo y ruta.' },
    ],
    aiTitle: 'Enviar a la IA', aiLead: "Pregunta con tus registros, precisa la respuesta y recupera el plan. Una conversación de ejemplo de unos 45 segundos.",
    you: 'Tú', reply: 'Respuesta',
    turns: [
      { prompt: "Prepara la próxima semana con estos registros de sueño y actividad. Conserva los descansos y marca los datos ausentes.", answer: "Organizaré los registros de ejemplo sin inventar mediciones. Los días sin datos se marcan como no proporcionados.\n\nEl borrador combina carrera suave, ciclismo de recuperación, tempo e intervalos con descansos. Cada sesión conserva calentamiento y vuelta a la calma. Puedes seguir ajustando sus pasos antes de recuperar el plan." },
      { prompt: "Deja la primera carrera suave en 40 minutos, con calentamiento y vuelta a la calma.", answer: "Son 6 minutos de calentamiento, 28 de carrera suave y 6 de vuelta a la calma.\n\nLas otras sesiones y los descansos se mantienen. Puedes revisar cada paso y cambiar las fechas en ZeppBridge antes de enviar el plan al reloj." },
    ],
    beats: [
      { id: 'plan', title: 'Plan semanal', text: 'Siete días, cada uno de entreno o de descanso.' },
      { id: 'arrange', title: 'Ordenar y borrar', text: 'Arrastra para cambiar dos días, o borra una carta.' },
      { id: 'prompt', title: 'Pregunta propia', text: 'Puedes editar el texto antes de enviarlo.' },
      { id: 'types', title: 'Fechas y tipos', text: 'Marca un rango de fechas y luego los tipos de entreno.' },
    ],
    settingsTitle: 'Salidas y ajustes', settingsLead: 'Están en el mismo tablero. Ninguno tiene página propia.',
    settings: [
      { id: 'mcp', title: 'MCP', text: 'Otras herramientas leen el archivo por el MCP local de solo lectura.' },
      { id: 'api', title: 'API local', text: 'Solo en 127.0.0.1. Solo lectura.' },
      { id: 'timezone', title: 'Zona horaria', text: 'El mismo registro muestra la fecha en la zona elegida.' },
      { id: 'units', title: 'Unidades', text: 'Distancia y ritmo usan las unidades elegidas.' },
      { id: 'time', title: 'Hora', text: 'El formato de la hora se cambia aquí.' },
      { id: 'year', title: 'Año', text: 'Abre el archivo por año.' },
      { id: 'range', title: 'Rango', text: 'Elige las fechas de inicio y fin.' },
      { id: 'events', title: 'Eventos', text: 'Anota un hecho en un día, junto al sueño y los entrenos.' },
    ],
    demoTitle: 'Pruébalo tú.', demoLead: 'Un año de registros ficticios. Los cambios se quedan en este ejemplo.',
    demoStart: 'Clic para empezar', demoReset: 'Restablecer',
    demoTabs: ['Archivo', 'Sueño', 'Entrenos', 'Enviar a la IA', 'Plan'],
    back: 'Volver a la introducción',
    downloadTitle: 'Instalar en este ordenador', downloadLead: 'Gratis y de código abierto. La versión v3 aún no está publicada.',
    downloadPending: 'La versión v3 aún no está publicada',
    install: 'Ejecuta el instalador de Windows. Arrastra la app de macOS a Aplicaciones. Elige un paquete para Linux.',
    system: 'Sistema',
  }),
  fr: pack({
    title: ['Sommeil, séances, récupération', 'sur cet ordinateur.'],
    lead: 'Synchronisez Zepp vers cette machine. Vue d’ensemble, stades de sommeil, comparaison des séances et plan au même endroit.',
    nav: { product: 'Produit', motion: 'Mouvement', try: 'Essayer', download: 'Télécharger', menu: 'Ouvrir le menu' },
    groups: { records: 'Relevés', ai: 'Envoyer à l’IA', connect: 'Sorties' },
    links: { overview: 'Vue d’ensemble', sleep: 'Sommeil et récupération', workouts: 'Séances', ask: 'Échange', plan: 'Plan', arrange: 'Ranger les cartes', mcp: 'MCP', api: 'API locale', settings: 'Réglages' },
    themes: ['Sombre', 'Clair', 'Système'],
    motionTitle: 'Mouvement', motionLead: "Cinq interactions complètes, jouées l’une après l’autre.",
    motions: [
      { id: "glass", title: "Verre inférieur", text: "Appuyez, glissez, relâchez. La lentille suit le pointeur et réfracte le fond." },
      { id: "poker", title: "Choisir et retourner", text: "7 jours, 1 mois, 6 mois, puis retour. Touchez le vide pour ranger les cartes." },
      { id: "seasons", title: "Quatre indicateurs", text: "Ajoutez quatre indicateurs, retrouvez-les à l’accueil, puis retirez-les." },
      { id: "notes", title: "Notes et rebond", text: "Ouvrez la note de durée du sommeil, soulevez une carte et relâchez-la." },
      { id: "box", title: "Boîte", text: "La boîte s’ouvre, reçoit une carte et se referme." },
    ],
    recordsTitle: 'Relevés',
    records: [
      { id: 'overview', title: 'Vue d’ensemble', text: 'Fréquence au repos, VFC, score de sommeil et pas sur la même page.' },
      { id: 'sleep', title: 'Sommeil', text: 'Durée, score et stades de chaque nuit. Le non mesuré reste vide.' },
      { id: 'workouts', title: 'Séances', text: 'Cette séance face à vos distances proches, avec fréquence, allure et tracé.' },
    ],
    aiTitle: 'Envoyer à l’IA', aiLead: "Posez une question avec vos données, précisez la réponse, puis récupérez le plan. Un exemple complet en environ 45 secondes.",
    you: 'Vous', reply: 'Réponse',
    turns: [
      { prompt: "Prépare la semaine à venir avec ces données de sommeil et d’activité. Garde les repos et signale les mesures absentes.", answer: "Je vais organiser ces données d’exemple sans inventer les mesures absentes. Les jours sans données restent indiqués comme non fournis.\n\nLe brouillon associe course facile, vélo de récupération, tempo et intervalles avec des repos. Chaque séance conserve son échauffement et son retour au calme. Les étapes restent modifiables." },
      { prompt: "Passe la première course facile à 40 minutes, avec échauffement et retour au calme.", answer: "Elle comprend 6 minutes d’échauffement, 28 de course facile et 6 de retour au calme.\n\nLes autres séances et les repos restent inchangés. Dans ZeppBridge, tu pourras vérifier les étapes et déplacer les dates avant de décider de l’envoi à la montre." },
    ],
    beats: [
      { id: 'plan', title: 'Plan de la semaine', text: 'Sept jours, chacun en séance ou en repos.' },
      { id: 'arrange', title: 'Ranger et supprimer', text: 'Glissez pour échanger deux jours, ou supprimez une carte.' },
      { id: 'prompt', title: 'Question personnalisée', text: 'Vous pouvez modifier le texte avant l’envoi.' },
      { id: 'types', title: 'Dates et types', text: 'Cochez une plage de dates, puis les types de séance.' },
    ],
    settingsTitle: 'Sorties et réglages', settingsLead: 'Tout est sur le même plateau. Aucune page séparée.',
    settings: [
      { id: 'mcp', title: 'MCP', text: 'D’autres outils lisent l’archive via le MCP local en lecture seule.' },
      { id: 'api', title: 'API locale', text: 'Liée à 127.0.0.1. Lecture seule.' },
      { id: 'timezone', title: 'Fuseau', text: 'Le même relevé affiche sa date dans le fuseau choisi.' },
      { id: 'units', title: 'Unités', text: 'Distance et allure utilisent les unités choisies.' },
      { id: 'time', title: 'Heure', text: 'Le format de l’heure se change ici.' },
      { id: 'year', title: 'Année', text: 'Ouvrez l’archive par année.' },
      { id: 'range', title: 'Plage', text: 'Choisissez les dates de début et de fin.' },
      { id: 'events', title: 'Événements', text: 'Notez un fait sur un jour, à côté du sommeil et des séances.' },
    ],
    demoTitle: 'Cliquez vous-même.', demoLead: 'Un an de données fictives. Les changements restent dans cet exemple.',
    demoStart: 'Cliquer pour commencer', demoReset: 'Réinitialiser',
    demoTabs: ['Archive', 'Sommeil', 'Séances', 'Envoyer à l’IA', 'Plan'],
    back: 'Retour à l’introduction',
    downloadTitle: 'Installer sur cet ordinateur', downloadLead: 'Gratuit et ouvert. La version v3 n’est pas encore publiée.',
    downloadPending: 'La version v3 n’est pas encore publiée',
    install: 'Lancez l’installateur Windows. Glissez l’app macOS dans Applications. Choisissez un paquet Linux.',
    system: 'Système',
  }),
  de: pack({
    title: ['Schlaf, Training, Erholung', 'auf diesem Computer.'],
    lead: 'Von Zepp auf diesen Rechner synchronisieren. Überblick, Schlafphasen, Trainingsvergleich und Plan an einem Ort.',
    nav: { product: 'Produkt', motion: 'Bewegung', try: 'Ausprobieren', download: 'Download', menu: 'Menü öffnen' },
    groups: { records: 'Aufzeichnungen', ai: 'An KI geben', connect: 'Weitergeben' },
    links: { overview: 'Überblick', sleep: 'Schlaf und Erholung', workouts: 'Training', ask: 'Austausch', plan: 'Plan', arrange: 'Karten ordnen', mcp: 'MCP', api: 'Lokale API', settings: 'Einstellungen' },
    themes: ['Dunkel', 'Hell', 'System'],
    motionTitle: 'Bewegung', motionLead: "Fünf vollständige Interaktionen, nacheinander abgespielt.",
    motions: [
      { id: "glass", title: "Glasnavigation", text: "Drücken, ziehen, loslassen. Die Linse folgt dem Zeiger und bricht den Hintergrund." },
      { id: "poker", title: "Tage wählen und umdrehen", text: "7 Tage, 1 Monat, 6 Monate und zurück. Tippe daneben, um die Karten einzusammeln." },
      { id: "seasons", title: "Vier feste Kennzahlen", text: "Vier Kennzahlen hinzufügen, auf der Startseite ansehen und einzeln entfernen." },
      { id: "notes", title: "Hinweise und Rückfedern", text: "Öffne den Hinweis zur Schlafdauer, ziehe eine Karte und lasse sie los." },
      { id: "box", title: "Sammelbox", text: "Die Box öffnet sich, nimmt eine Karte auf und schließt sich." },
    ],
    recordsTitle: 'Aufzeichnungen',
    records: [
      { id: 'overview', title: 'Überblick', text: 'Ruhepuls, HRV, Schlafwert und Schritte auf einer Seite.' },
      { id: 'sleep', title: 'Schlaf', text: 'Dauer, Wert und Phasen jeder Nacht. Ungemessenes bleibt leer.' },
      { id: 'workouts', title: 'Training', text: 'Diese Einheit gegen eigene ähnliche Distanzen, mit Puls, Tempo und Strecke.' },
    ],
    aiTitle: 'An KI geben', aiLead: "Frage mit deinen Aufzeichnungen, passe die Antwort an und übernimm den Plan. Ein vollständiges Beispiel in etwa 45 Sekunden.",
    you: 'Du', reply: 'Antwort',
    turns: [
      { prompt: "Plane die kommende Woche anhand dieser Schlaf- und Trainingsdaten. Behalte Ruhetage und kennzeichne fehlende Messwerte.", answer: "Ich ordne diese Beispieldaten, ohne fehlende Messwerte zu erfinden. Tage ohne Daten bleiben als nicht vorhanden gekennzeichnet.\n\nDer Entwurf verbindet lockeres Laufen, Erholungsradfahren, Tempolauf und Intervalle mit Ruhetagen. Aufwärmen und Abkühlen bleiben eigene Schritte. Du kannst den Entwurf weiter anpassen." },
      { prompt: "Ändere den ersten lockeren Lauf auf 40 Minuten mit Aufwärmen und Abkühlen.", answer: "Er umfasst 6 Minuten Aufwärmen, 28 Minuten lockeres Laufen und 6 Minuten Abkühlen.\n\nDie anderen Einheiten und Ruhetage bleiben bestehen. In ZeppBridge kannst du die Schritte prüfen und Tage verschieben, bevor du über die Übertragung an die Uhr entscheidest." },
    ],
    beats: [
      { id: 'plan', title: 'Wochenplan', text: 'Sieben Tage, jeder als Training oder Ruhe.' },
      { id: 'arrange', title: 'Ordnen und löschen', text: 'Ziehen tauscht zwei Tage. Eine Karte lässt sich löschen.' },
      { id: 'prompt', title: 'Eigene Frage', text: 'Den Text kannst du vor dem Senden ändern.' },
      { id: 'types', title: 'Datum und Typen', text: 'Zuerst den Zeitraum, dann die Trainingsarten.' },
    ],
    settingsTitle: 'Weitergabe und Einstellungen', settingsLead: 'Alles auf einer Fläche. Keine eigene Seite.',
    settings: [
      { id: 'mcp', title: 'MCP', text: 'Andere Werkzeuge lesen das Archiv über das lokale Nur-Lese-MCP.' },
      { id: 'api', title: 'Lokale API', text: 'Nur an 127.0.0.1. Nur lesen.' },
      { id: 'timezone', title: 'Zeitzone', text: 'Derselbe Eintrag zeigt das Datum in der gewählten Zone.' },
      { id: 'units', title: 'Einheiten', text: 'Distanz und Tempo nutzen die gewählten Einheiten.' },
      { id: 'time', title: 'Zeit', text: 'Das Zeitformat wird hier geändert.' },
      { id: 'year', title: 'Jahr', text: 'Das Archiv nach Jahr öffnen.' },
      { id: 'range', title: 'Bereich', text: 'Start- und Enddatum wählen.' },
      { id: 'events', title: 'Lebensereignisse', text: 'Ein Ereignis auf einen Tag schreiben, neben Schlaf und Training.' },
    ],
    demoTitle: 'Selbst klicken.', demoLead: 'Ein Jahr erfundener Daten. Änderungen bleiben in diesem Beispiel.',
    demoStart: 'Klicken zum Start', demoReset: 'Beispiel zurücksetzen',
    demoTabs: ['Archiv', 'Schlaf', 'Training', 'An KI geben', 'Plan'],
    back: 'Zurück zur Einleitung',
    downloadTitle: 'Auf diesem Computer installieren', downloadLead: 'Kostenlos und quelloffen. Die Version v3 ist noch nicht veröffentlicht.',
    downloadPending: 'Die Version v3 ist noch nicht veröffentlicht',
    install: 'Windows-Setup starten. Die macOS-App in Programme ziehen. Für Linux ein Paket wählen.',
    system: 'System',
  }),
  nl: pack({
    title: ['Slaap, training, herstel', 'op deze computer.'],
    lead: 'Synchroniseer van Zepp naar deze machine. Overzicht, slaapfases, trainingsvergelijking en plan op één plek.',
    nav: { product: 'Product', motion: 'Beweging', try: 'Probeer', download: 'Download', menu: 'Menu openen' },
    groups: { records: 'Gegevens', ai: 'Naar AI', connect: 'Doorgeven' },
    links: { overview: 'Overzicht', sleep: 'Slaap en herstel', workouts: 'Training', ask: 'Uitwisseling', plan: 'Plan', arrange: 'Kaarten ordenen', mcp: 'MCP', api: 'Lokale API', settings: 'Instellingen' },
    themes: ['Donker', 'Licht', 'Systeem'],
    motionTitle: 'Beweging', motionLead: "Vijf volledige interacties, achter elkaar afgespeeld.",
    motions: [
      { id: "glass", title: "Glazen navigatie", text: "Druk, sleep en laat los. De lens volgt je aanwijzer en breekt de achtergrond." },
      { id: "poker", title: "Dagen kiezen en omdraaien", text: "7 dagen, 1 maand, 6 maanden en terug. Tik naast de kaarten om ze te verzamelen." },
      { id: "seasons", title: "Vier vaste metingen", text: "Voeg vier metingen toe, bekijk ze op de startpagina en verwijder ze één voor één." },
      { id: "notes", title: "Notities en terugveren", text: "Open de notitie over slaapduur, til een kaart op en laat hem los." },
      { id: "box", title: "Verzameldoos", text: "De doos gaat open, ontvangt een kaart en sluit weer." },
    ],
    recordsTitle: 'Gegevens',
    records: [
      { id: 'overview', title: 'Overzicht', text: 'Rusthartslag, HRV, slaapscore en stappen op één pagina.' },
      { id: 'sleep', title: 'Slaap', text: 'Duur, score en fases per nacht. Niet gemeten blijft leeg.' },
      { id: 'workouts', title: 'Training', text: 'Deze sessie tegen je eigen vergelijkbare afstanden, met hartslag, tempo en route.' },
    ],
    aiTitle: 'Naar AI', aiLead: "Stel een vraag met je gegevens, verfijn het antwoord en haal het plan op. Een volledig voorbeeld in ongeveer 45 seconden.",
    you: 'Jij', reply: 'Antwoord',
    turns: [
      { prompt: "Plan de komende week met deze slaap- en trainingsgegevens. Behoud rustdagen en markeer ontbrekende metingen.", answer: "Ik orden deze voorbeeldgegevens zonder ontbrekende metingen te verzinnen. Dagen zonder gegevens blijven als niet beschikbaar gemarkeerd.\n\nHet concept combineert rustig hardlopen, herstelfietsen, tempolopen en intervallen met rustdagen. Warming-up en cooling-down blijven aparte stappen. Je kunt het concept verder aanpassen." },
      { prompt: "Maak de eerste rustige loop 40 minuten, met warming-up en cooling-down.", answer: "Dat wordt 6 minuten warming-up, 28 minuten rustig lopen en 6 minuten cooling-down.\n\nDe andere trainingen en rustdagen blijven staan. In ZeppBridge kun je de stappen controleren en datums wisselen voordat je beslist over verzending naar je horloge." },
    ],
    beats: [
      { id: 'plan', title: 'Weekplan', text: 'Zeven dagen, elk een training of rust.' },
      { id: 'arrange', title: 'Ordenen en wissen', text: 'Sleep om twee dagen te wisselen, of wis een kaart.' },
      { id: 'prompt', title: 'Eigen vraag', text: 'De tekst kun je wijzigen voor het versturen.' },
      { id: 'types', title: 'Datums en typen', text: 'Vink eerst een periode aan, dan de trainingstypen.' },
    ],
    settingsTitle: 'Doorgeven en instellingen', settingsLead: 'Alles op één bord. Geen aparte pagina.',
    settings: [
      { id: 'mcp', title: 'MCP', text: 'Andere tools lezen het archief via de lokale alleen-lezen MCP.' },
      { id: 'api', title: 'Lokale API', text: 'Alleen op 127.0.0.1. Alleen lezen.' },
      { id: 'timezone', title: 'Tijdzone', text: 'Dezelfde regel toont de datum in de gekozen zone.' },
      { id: 'units', title: 'Eenheden', text: 'Afstand en tempo gebruiken de gekozen eenheden.' },
      { id: 'time', title: 'Tijd', text: 'De tijdnotatie wijzig je hier.' },
      { id: 'year', title: 'Jaar', text: 'Open het archief per jaar.' },
      { id: 'range', title: 'Bereik', text: 'Kies begin- en einddatum.' },
      { id: 'events', title: 'Gebeurtenissen', text: 'Schrijf een gebeurtenis op een dag, naast slaap en training.' },
    ],
    demoTitle: 'Klik er zelf doorheen.', demoLead: 'Een jaar fictieve gegevens. Wijzigingen blijven in dit voorbeeld.',
    demoStart: 'Klik om te starten', demoReset: 'Voorbeeld resetten',
    demoTabs: ['Archief', 'Slaap', 'Training', 'Naar AI', 'Plan'],
    back: 'Terug naar de inleiding',
    downloadTitle: 'Installeren op deze computer', downloadLead: 'Gratis en open source. Versie v3 is nog niet gepubliceerd.',
    downloadPending: 'Versie v3 is nog niet gepubliceerd',
    install: 'Start het Windows-installatieprogramma. Sleep de macOS-app naar Programma’s. Kies een Linux-pakket.',
    system: 'Systeem',
  }),
  'pt-BR': pack({
    title: ['Sono, treinos e recuperação', 'neste computador.'],
    lead: 'Sincronize do Zepp para esta máquina. Visão geral, fases do sono, comparação de treinos e plano no mesmo lugar.',
    nav: { product: 'Produto', motion: 'Movimento', try: 'Experimentar', download: 'Baixar', menu: 'Abrir menu' },
    groups: { records: 'Registros', ai: 'Enviar à IA', connect: 'Saídas' },
    links: { overview: 'Visão geral', sleep: 'Sono e recuperação', workouts: 'Treinos', ask: 'Troca', plan: 'Plano', arrange: 'Ordenar cartas', mcp: 'MCP', api: 'API local', settings: 'Ajustes' },
    themes: ['Escuro', 'Claro', 'Sistema'],
    motionTitle: 'Movimento', motionLead: "Cinco interações completas, reproduzidas em sequência.",
    motions: [
      { id: "glass", title: "Vidro inferior", text: "Pressione, arraste e solte. A lente acompanha o ponteiro e refrata o fundo." },
      { id: "poker", title: "Escolher dias e virar", text: "7 dias, 1 mês, 6 meses e de volta. Toque no espaço vazio para recolher as cartas." },
      { id: "seasons", title: "Quatro métricas fixas", text: "Adicione quatro métricas, veja-as no início e remova uma por uma." },
      { id: "notes", title: "Notas e retorno", text: "Abra a nota de duração do sono, arraste uma carta e solte." },
      { id: "box", title: "Caixa", text: "A caixa abre, recebe uma carta e fecha." },
    ],
    recordsTitle: 'Registros',
    records: [
      { id: 'overview', title: 'Visão geral', text: 'Frequência em repouso, VFC, nota do sono e passos na mesma página.' },
      { id: 'sleep', title: 'Sono', text: 'Duração, nota e fases de cada noite. O que não foi medido fica vazio.' },
      { id: 'workouts', title: 'Treinos', text: 'Esta sessão contra distâncias parecidas suas, com frequência, ritmo e rota.' },
    ],
    aiTitle: 'Enviar à IA', aiLead: "Pergunte com seus registros, refine a resposta e traga o plano de volta. Uma conversa completa em cerca de 45 segundos.",
    you: 'Você', reply: 'Resposta',
    turns: [
      { prompt: "Monte a próxima semana com estes registros de sono e treino. Mantenha os descansos e marque as medições ausentes.", answer: "Vou organizar estes dados de exemplo sem inventar medições ausentes. Dias sem dados continuam marcados como não fornecidos.\n\nO rascunho combina corrida leve, ciclismo de recuperação, ritmo e intervalos com descanso. Aquecimento e desaquecimento ficam em etapas separadas. Você pode continuar ajustando o plano." },
      { prompt: "Deixe a primeira corrida leve com 40 minutos, incluindo aquecimento e desaquecimento.", answer: "São 6 minutos de aquecimento, 28 de corrida leve e 6 de desaquecimento.\n\nOs outros treinos e descansos permanecem. No ZeppBridge, você pode conferir cada etapa e trocar datas antes de decidir se envia o plano ao relógio." },
    ],
    beats: [
      { id: 'plan', title: 'Plano da semana', text: 'Sete dias, cada um de treino ou de descanso.' },
      { id: 'arrange', title: 'Ordenar e apagar', text: 'Arraste para trocar dois dias, ou apague uma carta.' },
      { id: 'prompt', title: 'Pergunta própria', text: 'Dá para editar o texto antes de enviar.' },
      { id: 'types', title: 'Datas e tipos', text: 'Marque um intervalo e depois os tipos de treino.' },
    ],
    settingsTitle: 'Saídas e ajustes', settingsLead: 'Tudo no mesmo quadro. Nenhum tem página própria.',
    settings: [
      { id: 'mcp', title: 'MCP', text: 'Outras ferramentas leem o arquivo pelo MCP local somente leitura.' },
      { id: 'api', title: 'API local', text: 'Só em 127.0.0.1. Somente leitura.' },
      { id: 'timezone', title: 'Fuso', text: 'O mesmo registro mostra a data no fuso escolhido.' },
      { id: 'units', title: 'Unidades', text: 'Distância e ritmo usam as unidades escolhidas.' },
      { id: 'time', title: 'Hora', text: 'O formato da hora muda aqui.' },
      { id: 'year', title: 'Ano', text: 'Abra o arquivo por ano.' },
      { id: 'range', title: 'Intervalo', text: 'Escolha as datas de início e fim.' },
      { id: 'events', title: 'Eventos', text: 'Anote um fato num dia, ao lado do sono e dos treinos.' },
    ],
    demoTitle: 'Clique você mesmo.', demoLead: 'Um ano de registros fictícios. As mudanças ficam neste exemplo.',
    demoStart: 'Clique para começar', demoReset: 'Redefinir exemplo',
    demoTabs: ['Arquivo', 'Sono', 'Treinos', 'Enviar à IA', 'Plano'],
    back: 'Voltar à introdução',
    downloadTitle: 'Instalar neste computador', downloadLead: 'Grátis e de código aberto. A versão v3 ainda não foi publicada.',
    downloadPending: 'A versão v3 ainda não foi publicada',
    install: 'Execute o instalador do Windows. Arraste o app do macOS para Aplicativos. Escolha um pacote Linux.',
    system: 'Sistema',
  }),
  'pt-PT': pack({
    title: ['Sono, treinos e recuperação', 'neste computador.'],
    lead: 'Sincroniza do Zepp para esta máquina. Resumo, fases do sono, comparação de treinos e plano no mesmo sítio.',
    nav: { product: 'Produto', motion: 'Movimento', try: 'Experimentar', download: 'Transferir', menu: 'Abrir menu' },
    groups: { records: 'Registos', ai: 'Enviar à IA', connect: 'Saídas' },
    links: { overview: 'Resumo', sleep: 'Sono e recuperação', workouts: 'Treinos', ask: 'Troca', plan: 'Plano', arrange: 'Ordenar cartas', mcp: 'MCP', api: 'API local', settings: 'Definições' },
    themes: ['Escuro', 'Claro', 'Sistema'],
    motionTitle: 'Movimento', motionLead: "Cinco interações completas, reproduzidas em sequência.",
    motions: [
      { id: "glass", title: "Vidro inferior", text: "Prime, arrasta e larga. A lente acompanha o ponteiro e refrata o fundo." },
      { id: "poker", title: "Escolher dias e virar", text: "7 dias, 1 mês, 6 meses e de volta. Toca no espaço vazio para recolher as cartas." },
      { id: "seasons", title: "Quatro métricas fixas", text: "Adiciona quatro métricas, vê-as no início e remove-as uma a uma." },
      { id: "notes", title: "Notas e retorno", text: "Abre a nota da duração do sono, arrasta uma carta e larga-a." },
      { id: "box", title: "Caixa", text: "A caixa abre, recebe uma carta e fecha." },
    ],
    recordsTitle: 'Registos',
    records: [
      { id: 'overview', title: 'Resumo', text: 'Frequência em repouso, VFC, nota do sono e passos na mesma página.' },
      { id: 'sleep', title: 'Sono', text: 'Duração, nota e fases de cada noite. O que não foi medido fica vazio.' },
      { id: 'workouts', title: 'Treinos', text: 'Esta sessão contra distâncias parecidas tuas, com frequência, ritmo e rota.' },
    ],
    aiTitle: 'Enviar à IA', aiLead: "Pergunta com os teus registos, ajusta a resposta e recupera o plano. Uma conversa completa em cerca de 45 segundos.",
    you: 'Tu', reply: 'Resposta',
    turns: [
      { prompt: "Prepara a próxima semana com estes registos de sono e treino. Mantém os descansos e assinala as medições em falta.", answer: "Vou organizar estes dados de exemplo sem inventar medições em falta. Os dias sem dados continuam assinalados como não fornecidos.\n\nO rascunho combina corrida leve, ciclismo de recuperação, ritmo e intervalos com descanso. Aquecimento e retorno à calma ficam em etapas separadas. Podes continuar a ajustar o plano." },
      { prompt: "Deixa a primeira corrida leve com 40 minutos, incluindo aquecimento e retorno à calma.", answer: "São 6 minutos de aquecimento, 28 de corrida leve e 6 de retorno à calma.\n\nOs outros treinos e descansos mantêm-se. No ZeppBridge, podes rever cada etapa e trocar datas antes de decidir se envias o plano ao relógio." },
    ],
    beats: [
      { id: 'plan', title: 'Plano da semana', text: 'Sete dias, cada um de treino ou de descanso.' },
      { id: 'arrange', title: 'Ordenar e apagar', text: 'Arrasta para trocar dois dias, ou apaga uma carta.' },
      { id: 'prompt', title: 'Pergunta própria', text: 'Podes editar o texto antes de enviar.' },
      { id: 'types', title: 'Datas e tipos', text: 'Marca um intervalo e depois os tipos de treino.' },
    ],
    settingsTitle: 'Saídas e definições', settingsLead: 'Tudo no mesmo quadro. Nenhum tem página própria.',
    settings: [
      { id: 'mcp', title: 'MCP', text: 'Outras ferramentas leem o arquivo pelo MCP local só de leitura.' },
      { id: 'api', title: 'API local', text: 'Só em 127.0.0.1. Só leitura.' },
      { id: 'timezone', title: 'Fuso', text: 'O mesmo registo mostra a data no fuso escolhido.' },
      { id: 'units', title: 'Unidades', text: 'Distância e ritmo usam as unidades escolhidas.' },
      { id: 'time', title: 'Hora', text: 'O formato da hora muda aqui.' },
      { id: 'year', title: 'Ano', text: 'Abre o arquivo por ano.' },
      { id: 'range', title: 'Intervalo', text: 'Escolhe as datas de início e fim.' },
      { id: 'events', title: 'Eventos', text: 'Anota um facto num dia, ao lado do sono e dos treinos.' },
    ],
    demoTitle: 'Experimenta tu.', demoLead: 'Um ano de registos fictícios. As alterações ficam neste exemplo.',
    demoStart: 'Clica para começar', demoReset: 'Repor exemplo',
    demoTabs: ['Arquivo', 'Sono', 'Treinos', 'Enviar à IA', 'Plano'],
    back: 'Voltar à introdução',
    downloadTitle: 'Instalar neste computador', downloadLead: 'Grátis e de código aberto. A versão v3 ainda não foi publicada.',
    downloadPending: 'A versão v3 ainda não foi publicada',
    install: 'Executa o instalador do Windows. Arrasta a app do macOS para Aplicações. Escolhe um pacote Linux.',
    system: 'Sistema',
  }),
  ru: pack({
    title: ['Сон, тренировки, восстановление', 'на этом компьютере.'],
    lead: 'Синхронизация из Zepp на этот компьютер. Обзор, фазы сна, сравнение тренировок и план в одном месте.',
    nav: { product: 'Продукт', motion: 'Движение', try: 'Попробовать', download: 'Скачать', menu: 'Открыть меню' },
    groups: { records: 'Записи', ai: 'Отдать ИИ', connect: 'Наружу' },
    links: { overview: 'Обзор', sleep: 'Сон и восстановление', workouts: 'Тренировки', ask: 'Обмен', plan: 'План', arrange: 'Разложить карты', mcp: 'MCP', api: 'Локальный API', settings: 'Настройки' },
    themes: ['Тёмная', 'Светлая', 'Система'],
    motionTitle: 'Движение', motionLead: "Пять полных взаимодействий, одно за другим.",
    motions: [
      { id: "glass", title: "Стеклянная навигация", text: "Нажмите, потяните и отпустите. Линза следует за указателем и преломляет фон." },
      { id: "poker", title: "Выбор дней и переворот", text: "7 дней, 1 месяц, 6 месяцев и обратно. Нажмите рядом, чтобы собрать карты." },
      { id: "seasons", title: "Четыре показателя", text: "Добавьте четыре показателя, посмотрите их на главной и удалите по одному." },
      { id: "notes", title: "Подсказки и возврат", text: "Откройте пояснение длительности сна, потяните карту и отпустите." },
      { id: "box", title: "Коробка", text: "Коробка открывается, принимает карту и закрывается." },
    ],
    recordsTitle: 'Записи',
    records: [
      { id: 'overview', title: 'Обзор', text: 'Пульс покоя, ВСР, оценка сна и шаги на одной странице.' },
      { id: 'sleep', title: 'Сон', text: 'Длительность, оценка и фазы каждой ночи. Неизмеренное остаётся пустым.' },
      { id: 'workouts', title: 'Тренировки', text: 'Эта сессия против ваших близких дистанций, с пульсом, темпом и треком.' },
    ],
    aiTitle: 'Отдать ИИ', aiLead: "Задайте вопрос с записями, уточните ответ и верните план. Полный пример диалога примерно за 45 секунд.",
    you: 'Вы', reply: 'Ответ',
    turns: [
      { prompt: "Составь ближайшую неделю по этим записям сна и тренировок. Сохрани отдых и отметь отсутствующие измерения.", answer: "Я упорядочу эти примерные данные, не выдумывая отсутствующие измерения. Дни без данных останутся отмечены как не предоставленные.\n\nЧерновик сочетает лёгкий бег, восстановительный велозаезд, темповый бег и интервалы с отдыхом. Разминка и заминка остаются отдельными этапами. План можно уточнять дальше." },
      { prompt: "Сделай первую лёгкую пробежку на 40 минут, включая разминку и заминку.", answer: "Это 6 минут разминки, 28 минут лёгкого бега и 6 минут заминки.\n\nОстальные занятия и отдых сохранены. В ZeppBridge можно проверить каждый этап и поменять даты, прежде чем решить, отправлять ли план на часы." },
    ],
    beats: [
      { id: 'plan', title: 'План недели', text: 'Семь дней, каждый тренировка или отдых.' },
      { id: 'arrange', title: 'Разложить и удалить', text: 'Перетащите, чтобы поменять два дня, или удалите карту.' },
      { id: 'prompt', title: 'Свой вопрос', text: 'Текст можно изменить перед отправкой.' },
      { id: 'types', title: 'Даты и типы', text: 'Отметьте диапазон дат, затем типы тренировок.' },
    ],
    settingsTitle: 'Вывод и настройки', settingsLead: 'Всё на одной доске. Отдельных страниц нет.',
    settings: [
      { id: 'mcp', title: 'MCP', text: 'Другие инструменты читают архив через локальный MCP только для чтения.' },
      { id: 'api', title: 'Локальный API', text: 'Только 127.0.0.1. Только чтение.' },
      { id: 'timezone', title: 'Часовой пояс', text: 'Та же запись показывает дату в выбранном поясе.' },
      { id: 'units', title: 'Единицы', text: 'Дистанция и темп в выбранных единицах.' },
      { id: 'time', title: 'Время', text: 'Формат времени меняется здесь.' },
      { id: 'year', title: 'Год', text: 'Открыть архив по году.' },
      { id: 'range', title: 'Диапазон', text: 'Выберите даты начала и конца.' },
      { id: 'events', title: 'События', text: 'Запишите событие на день рядом со сном и тренировками.' },
    ],
    demoTitle: 'Нажмите сами.', demoLead: 'Год вымышленных записей. Изменения остаются в этом примере.',
    demoStart: 'Нажмите, чтобы начать', demoReset: 'Сбросить пример',
    demoTabs: ['Архив', 'Сон', 'Тренировки', 'Отдать ИИ', 'План'],
    back: 'К введению',
    downloadTitle: 'Установить на этот компьютер', downloadLead: 'Бесплатно, с открытым кодом. Версия v3 ещё не опубликована.',
    downloadPending: 'Версия v3 ещё не опубликована',
    install: 'Запустите установщик Windows. Перетащите приложение macOS в «Программы». Для Linux выберите пакет.',
    system: 'Системная',
  }),
  'hi-IN': pack({
    title: ['नींद, कसरत, रिकवरी', 'इसी कंप्यूटर पर।'],
    lead: 'Zepp से इस मशीन पर सिंक करें। सार, नींद की अवस्थाएँ, कसरत की तुलना और योजना एक जगह।',
    nav: { product: 'उत्पाद', motion: 'गति', try: 'आज़माएँ', download: 'डाउनलोड', menu: 'मेनू खोलें' },
    groups: { records: 'रिकॉर्ड', ai: 'AI को दें', connect: 'बाहर' },
    links: { overview: 'सार', sleep: 'नींद और रिकवरी', workouts: 'कसरत', ask: 'आदान', plan: 'योजना', arrange: 'कार्ड सजाएँ', mcp: 'MCP', api: 'लोकल API', settings: 'सेटिंग' },
    themes: ['गहरा', 'हल्का', 'सिस्टम'],
    motionTitle: 'गति', motionLead: "पाँच पूरे इंटरैक्शन, एक के बाद एक।",
    motions: [
      { id: "glass", title: "नीचे का ग्लास", text: "दबाएँ, खींचें और छोड़ें। लेंस पॉइंटर के साथ चलता है और पृष्ठभूमि को अपवर्तित करता है।" },
      { id: "poker", title: "दिन चुनें और पलटें", text: "7 दिन, 1 महीना, 6 महीने और वापस। कार्ड समेटने के लिए खाली जगह दबाएँ।" },
      { id: "seasons", title: "चार पिन किए माप", text: "चार माप जोड़ें, होम पर देखें और एक-एक करके हटाएँ।" },
      { id: "notes", title: "नोट और वापसी", text: "नींद की अवधि का नोट खोलें, कार्ड खींचें और छोड़ें।" },
      { id: "box", title: "संग्रह बॉक्स", text: "बॉक्स खुलता है, कार्ड लेता है और बंद होता है।" },
    ],
    recordsTitle: 'रिकॉर्ड',
    records: [
      { id: 'overview', title: 'सार', text: 'विश्राम हृदय गति, HRV, नींद अंक और कदम एक पृष्ठ पर।' },
      { id: 'sleep', title: 'नींद', text: 'हर रात की अवधि, अंक और अवस्थाएँ। जहाँ माप नहीं, वहाँ खाली।' },
      { id: 'workouts', title: 'कसरत', text: 'यह सत्र आपकी मिलती दूरी से, हृदय गति, गति और मार्ग के साथ।' },
    ],
    aiTitle: 'AI को दें', aiLead: "रिकॉर्ड के साथ सवाल पूछें, उत्तर सुधारें और प्लान वापस लाएँ। लगभग 45 सेकंड की पूरी उदाहरण बातचीत।",
    you: 'आप', reply: 'उत्तर',
    turns: [
      { prompt: "इन नींद और व्यायाम रिकॉर्ड से अगला सप्ताह बनाएँ। आराम के दिन रखें और गायब माप चिह्नित करें।", answer: "मैं उदाहरण डेटा व्यवस्थित करूँगा, गायब माप नहीं गढ़ूँगा। जिन दिनों का डेटा नहीं है, वे नहीं दिया के रूप में चिह्नित रहेंगे।\n\nड्राफ्ट में हल्की दौड़, रिकवरी साइकिलिंग, टेम्पो और अंतराल के साथ आराम है। वार्म-अप और कूल-डाउन अलग चरण हैं। आप प्लान को आगे बदल सकते हैं।" },
      { prompt: "पहली हल्की दौड़ 40 मिनट की करें, वार्म-अप और कूल-डाउन सहित।", answer: "इसमें 6 मिनट वार्म-अप, 28 मिनट हल्की दौड़ और 6 मिनट कूल-डाउन है।\n\nबाकी अभ्यास और आराम वैसे ही हैं। ZeppBridge में हर चरण देखें और तारीख बदलें, फिर घड़ी पर भेजने का निर्णय लें।" },
    ],
    beats: [
      { id: 'plan', title: 'सप्ताह योजना', text: 'सात दिन, हर दिन कसरत या आराम।' },
      { id: 'arrange', title: 'सजाना और हटाना', text: 'खींचकर दो दिन बदलें, या एक कार्ड हटाएँ।' },
      { id: 'prompt', title: 'अपना प्रश्न', text: 'भेजने से पहले यह पाठ बदल सकते हैं।' },
      { id: 'types', title: 'तारीख और प्रकार', text: 'पहले तारीख सीमा, फिर कसरत के प्रकार चुनें।' },
    ],
    settingsTitle: 'बाहर और सेटिंग', settingsLead: 'सब एक पट्ट पर। किसी की अलग पृष्ठ नहीं।',
    settings: [
      { id: 'mcp', title: 'MCP', text: 'दूसरे औजार स्थानीय केवल-पढ़ने MCP से अभिलेख पढ़ते हैं।' },
      { id: 'api', title: 'लोकल API', text: 'केवल 127.0.0.1। केवल पढ़ना।' },
      { id: 'timezone', title: 'समय क्षेत्र', text: 'वही रिकॉर्ड चुने क्षेत्र में तारीख दिखाता है।' },
      { id: 'units', title: 'इकाई', text: 'दूरी और गति चुनी इकाई में।' },
      { id: 'time', title: 'समय', text: 'समय का प्रारूप यहीं बदलता है।' },
      { id: 'year', title: 'वर्ष', text: 'अभिलेख वर्ष के हिसाब से खोलें।' },
      { id: 'range', title: 'सीमा', text: 'आरंभ और अंत की तारीख चुनें।' },
      { id: 'events', title: 'जीवन घटना', text: 'किसी दिन एक बात लिखें, नींद और कसरत के साथ।' },
    ],
    demoTitle: 'खुद क्लिक करें।', demoLead: 'एक साल के काल्पनिक रिकॉर्ड। बदलाव इसी उदाहरण में रहते हैं।',
    demoStart: 'शुरू करने के लिए क्लिक', demoReset: 'उदाहरण रीसेट',
    demoTabs: ['अभिलेख', 'नींद', 'कसरत', 'AI को दें', 'योजना'],
    back: 'परिचय पर वापस',
    downloadTitle: 'इस कंप्यूटर पर स्थापित करें', downloadLead: 'मुफ़्त और ओपन सोर्स। v3 संस्करण अभी प्रकाशित नहीं है।',
    downloadPending: 'v3 संस्करण अभी प्रकाशित नहीं है',
    install: 'Windows इंस्टॉलर चलाएँ। macOS ऐप को Applications में रखें। Linux के लिए पैकेज चुनें।',
    system: 'सिस्टम',
  }),
};
