import type { LandingPack } from '../../composables/useLandingLocale';

const pack: LandingPack = {
  meta: {
    title: 'ZeppBridge · Van je pols naar je computer, van je computer naar AI',
    description: 'ZeppBridge haalt je Amazfit- en Zepp-gegevens uit de Zepp-cloud naar je eigen computer en zet ze klaar in één bestand voor je AI. Gratis en open source.',
    ogTitle: 'ZeppBridge · Van pols naar bureau. Van bureau naar AI.',
    ogDescription: 'Synchroniseer en bekijk je hartslag, slaap en trainingen lokaal, en geef ze met één klik aan de AI die je al gebruikt.',
  },
  copy: {
    nav: { home: 'ZeppBridge home', site: 'Sitenavigatie', demo: 'Demonstratie', features: 'Functies', ai: 'Naar AI', privacy: 'Privacy', download: 'Downloaden', github: 'GitHub', language: 'Taal', toDark: 'Naar donker', toLight: 'Naar licht' },
    downloads: {
      windows: { label: 'Downloaden voor Windows', hint: 'x64-installatieprogramma', msi: 'MSI voor beheerde installaties' },
      macos: { label: 'Downloaden voor macOS', hint: 'Apple Silicon' },
      linux: { label: 'Linux', previewBadge: 'Experimenteel', note: 'De CI bouwt deb, rpm, AppImage en Flatpak, maar niemand heeft inloggen en de sleutelbos al volledig getest op een echte Linux-desktop. Loop je ergens tegenaan? Open een issue.' },
      status: { loading: 'Nieuwste installatieprogramma zoeken', ready: 'Klik om direct te downloaden', fallback: 'Opent GitHub Releases, daar kies je het pakket' },
    },
    sample: 'Voorbeeld',
    hero: {
      eyebrow: 'Gratis · Open source · Blijft op je computer',
      titleLead: 'Van je pols naar je computer.',
      titleAccent: 'Van je computer naar AI.',
      lead: 'ZeppBridge haalt de hartslag, slaap en trainingen die je Amazfit heeft vastgelegd uit de Zepp-cloud naar je eigen computer, als archief dat je kunt lezen en overal mee naartoe kunt nemen. Heb je een vraag, kies dan een periode en geef die als één bestand aan een AI.',
      github: 'Bekijk de broncode op GitHub',
      pillars: ['Gesynchroniseerd naar je computer', 'Met één klik naar je AI'],
      meta: 'Gratis · Windows 10 / 11 · macOS (Apple Silicon) · Linux experimenteel',
      devices: 'Amazfit-apparaten die het al kent',
      toasts: [
        { title: 'Synchronisatie klaar', body: '1.284 nieuwe metingen, de laatste van vanochtend 07:12' },
        { title: '7 u 12 min geslapen', body: '18 minuten meer diepe slaap dan je gemiddelde van 30 dagen' },
        { title: 'Ingepakt voor je AI', body: 'Slaap, hartslag en HRV, laatste 7 dagen, één .md-bestand' },
        { title: 'Avondloop, 6,2 km', body: 'Route, tempo per kilometer en de hartslagcurve' },
        { title: 'Twee uur zonder hartslag', body: 'Het horloge zat niet om je pols. De grafiek blijft leeg, nooit 0.' },
      ],
      ask: { question: 'Hoe heb ik deze week geslapen vergeleken met vorige week?', file: 'ZeppBridge laatste 7 dagen.md' },
      starNudge: { title: 'Je download is gestart', copy: 'Heb je iets aan ZeppBridge? Een ster op GitHub helpt andere Amazfit-gebruikers het te vinden.', action: 'Ster geven', dismiss: 'Later' },
    },
    chapters: { sync: '01 · Naar je computer', ai: '02 · Naar je AI' },
    flap: {
      heading: 'Het hield nooit op met noteren',
      lead: 'Drie jaar om je pols levert ongeveer dit op. ZeppBridge haalt elke meting terug en zet ze per dag op een rij.',
      tiles: [
        { value: '1.096', label: 'nachten slaap' },
        { value: '742', label: 'trainingen met route' },
        { value: '1,5M', label: 'minuten hartslag' },
        { value: '9,8M', label: 'stappen' },
      ],
    },
    demo: {
      heading: 'Voelt als een app, niet als een spreadsheet',
      lead: 'Wissel van tabblad voor andere gegevens. Zet daarna de schakelaar om en zie hoe een ontbrekende meting eruit hoort te zien.',
      window: 'ZeppBridge · Overzicht',
      tabs: { heart: 'Hartslag', sleep: 'Slaap', steps: 'Stappen' },
      nav: ['Overzicht', 'Naar AI', 'Trainingen', 'Instellingen'],
      heart: { value: '62', unit: 'spm', caption: 'Vandaag per minuut. De piek in de avond is een loopje.' },
      sleep: { value: '7 u 12 min', caption: 'In slaap om 23:48, wakker om 07:00', stages: ['Wakker', 'REM', 'Licht', 'Diep'] },
      steps: { value: '11.406', unit: 'stappen', caption: 'Stappen per uur. Uren zonder lopen blijven leeg.' },
      gap: {
        label: 'Twee uur zonder horloge',
        honest: 'Leeg laten',
        zero: 'Vullen met 0',
        honestNote: 'Zo tekent ZeppBridge het: geen gegevens is geen gegevens, de lijn breekt.',
        zeroNote: 'Zo tekenen veel tools het: een duik naar nul die eruitziet als een noodgeval.',
      },
    },
    bento: {
      heading: 'Alles wat het nodig heeft. Niets wat niet.',
      lead: 'Elk onderdeel draait op je computer, zonder server van ons ertussen.',
      connect: { title: 'Drie manieren om binnen te komen', copy: 'Eerst de officiële autorisatie, uitgebreide gegevens voor meer meetwaarden, handmatig invoeren als terugval.', rows: ['Officiële Zepp-autorisatie', 'Uitgebreide gegevens', 'Handmatig invoeren'], states: ['Verbonden', 'Verbonden', 'Stand-by'] },
      local: { title: 'Eén map is alles', copy: 'De database staat in de map data naast de app. Kopieer die en je hebt een volledige back-up.' },
      export: { title: 'Neem het overal mee naartoe', copy: 'JSON, CSV, GPX en FIT, voor elke periode die je kiest.' },
      api: { title: 'Een deur voor scripts en AI-tools', copy: 'Opdrachtregel, MCP en een lokale alleen-lezen-API. Standaard uit, alleen op 127.0.0.1.', output: ['database        ok', 'laatste sync    vandaag 07:12', 'bij te halen    0 dagen'] },
      languages: { title: 'Tien talen', copy: 'Nederlands, Engels, Chinees, Spaans, Duits, Frans, twee soorten Portugees, Russisch en Hindi.' },
      theme: { title: 'Donker voorop, licht kan ook', copy: 'Volgt het systeem of je eigen keuze.', dark: 'Donker', light: 'Licht' },
    },
    ai: {
      heading: 'Iets vragen aan een AI? Kies wat die mag zien.',
      lead: 'Vink een paar soorten gegevens aan en ZeppBridge pakt ze in één .md-bestand. Sleep het in de AI die je al gebruikt en vraag het zoals je het een vriend zou vragen die al je metingen heeft gelezen.',
      pick: 'Deze keer voor de AI',
      chips: ['Slaap', 'Hartslag', 'HRV', 'Trainingen', 'Stress', 'Gewicht'],
      picked: '{n} soorten gekozen, laatste 7 dagen',
      file: 'ZeppBridge laatste 7 dagen.md',
      prompt: 'Heb ik deze week slechter geslapen dan vorige week? Waar kan dat aan liggen?',
      answer: 'Iets slechter: gemiddeld 38 minuten minder, vooral diepe slaap. Op dinsdag en donderdag trainde je \'s avonds, en die nachten zakte je hartslag trager. Probeer een week lang \'s middags te trainen.',
      note: 'Geen ingebouwde AI en geen extra account. Wat eruit gaat, hoeveel en wanneer gebeurt pas als jij klikt.',
    },
    privacy: {
      heading: 'Je gezondheidsgegevens staan op twee plekken',
      lead: 'In de Zepp-cloud en op je eigen computer. Een derde is er niet.',
      nodes: { watch: 'Horloge', cloud: 'Zepp-cloud', computer: 'Je computer', server: 'ZeppBridge-server', none: 'bestaat niet' },
      points: [
        { title: 'Tokens in de systeemkluis', copy: 'In Windows Referentiebeheer of de macOS-sleutelhanger, nooit in de gegevensmap.' },
        { title: 'Geen telemetrie', copy: 'Geen gebruiksmeting en geen gezondheidsgegevens verzameld.' },
        { title: 'Duidelijke herkomst', copy: 'Elke meting weet of die uit de officiële autorisatie of uit de uitgebreide gegevens komt.' },
      ],
    },
    connect: {
      heading: 'Drie manieren om te verbinden. Kies de makkelijkste.',
      lead: 'Begin met de officiële autorisatie. Voeg uitgebreide gegevens toe als je meer meetwaarden wilt.',
      recommended: 'Aanbevolen',
      paths: [
        { title: 'Officiële Zepp-autorisatie', copy: 'Log in bij Zepp in je gewone browser en geef toestemming.', detail: 'Google-, Xiaomi- en Apple-accounts werken. Slaap, hartslag, stappen, trainingen, PAI en gewicht worden gesynchroniseerd.' },
        { title: 'Uitgebreide gegevens', copy: 'Voegt HRV, bloedzuurstof, stress en paraatheid toe, die de officiële API niet biedt.', detail: 'Inloggen met e-mail of telefoonnummer. Het token staat alleen in je systeemkluis.' },
        { title: 'Handmatig invoeren', copy: 'De terugval als de andere twee niet lukken.', detail: 'Je plakt zelf een token. Bedoeld voor wie de API kent.' },
      ],
      note: 'Wat er synchroniseert, hangt af van wat je account in de Zepp-cloud heeft. Welke meetwaarden je ziet, hangt af van je apparaat en hoe je verbindt.',
    },
    final: {
      heading: 'Installeer het en zie wat je horloge nog weet',
      lead: 'Gratis, open source, zonder account.',
      facts: {
        channel: 'Stabiel kanaal, installatieprogramma\'s via GitHub Releases',
        systems: 'Windows 10 / 11 (x64) en macOS (Apple Silicon). Linux is experimenteel.',
        ai: 'Geen extra account nodig. Voor AI-vragen gebruik je de AI die je al hebt.',
        windows: 'Windows: het installatieprogramma is nog niet ondertekend. Zie je "Onbekende uitgever", kies dan "Meer informatie" en daarna "Toch uitvoeren".',
        macos: 'macOS: een niet-ondertekende build, dus de eerste start wordt geblokkeerd. Hoe je hem toestaat, staat in de readme op GitHub.',
      },
    },
    footer: {
      tagline: 'Een lokale brug voor Amazfit- en Zepp-gegevens.',
      disclaimer: 'ZeppBridge is een onafhankelijk opensourceproject en niet verbonden aan Zepp Health of Amazfit.',
      source: 'Broncode',
    },
  },
};

export default pack;
