import type { LandingPack } from '../../composables/useLandingLocale';

const pack: LandingPack = {
  meta: {
    title: 'ZeppBridge · Do pulso para o seu computador, do computador para a IA',
    description: 'O ZeppBridge traz seus dados do Amazfit e do Zepp da nuvem do Zepp para o seu próprio computador e deixa tudo pronto em um arquivo para a sua IA. Grátis e de código aberto.',
    ogTitle: 'ZeppBridge · Do pulso para a mesa. Da mesa para a IA.',
    ogDescription: 'Sincronize e veja localmente frequência cardíaca, sono e treinos, e entregue tudo com um clique à IA que você já usa.',
  },
  copy: {
    nav: { home: 'Início do ZeppBridge', site: 'Navegação do site', demo: 'Demonstração', features: 'Recursos', ai: 'Para a IA', privacy: 'Privacidade', download: 'Baixar', github: 'GitHub', language: 'Idioma', toDark: 'Mudar para escuro', toLight: 'Mudar para claro' },
    downloads: {
      windows: { label: 'Baixar para Windows', hint: 'Instalador x64', msi: 'MSI para instalações gerenciadas' },
      macos: { label: 'Baixar para macOS', hint: 'Apple Silicon' },
      linux: { label: 'Linux', previewBadge: 'Experimental', note: 'A CI gera deb, rpm, AppImage e Flatpak, mas ninguém testou ainda o login e o chaveiro de ponta a ponta em um desktop Linux de verdade. Algum problema? Abra uma issue.' },
      status: { loading: 'Procurando o instalador mais recente', ready: 'Clique para baixar direto', fallback: 'Abre o GitHub Releases, onde você escolhe o instalador' },
    },
    sample: 'Exemplo',
    hero: {
      eyebrow: 'Grátis · Código aberto · Fica no seu computador',
      titleLead: 'Do pulso para o seu computador.',
      titleAccent: 'Do computador direto para a IA.',
      lead: 'O ZeppBridge traz da nuvem do Zepp a frequência cardíaca, o sono e os treinos que o seu Amazfit registrou e guarda tudo no seu computador como um arquivo que você consegue ler e levar para qualquer lugar. Quando bater uma dúvida, você escolhe um período e entrega para uma IA em um único arquivo.',
      github: 'Ver o código no GitHub',
      pillars: ['Sincronizado no seu computador', 'Entregue à sua IA com um clique'],
      meta: 'Grátis · Windows 10 / 11 · macOS (Apple Silicon) · Linux experimental',
      devices: 'Aparelhos Amazfit que ele já reconhece',
      toasts: [
        { title: 'Sincronização concluída', body: '1.284 registros novos, o último de hoje às 07:12' },
        { title: 'Você dormiu 7 h 12 min', body: '18 minutos a mais de sono profundo que a sua média de 30 dias' },
        { title: 'Pronto para a sua IA', body: 'Sono, frequência cardíaca e HRV, últimos 7 dias, um arquivo .md' },
        { title: 'Corrida da noite, 6,2 km', body: 'Trajeto, ritmo por quilômetro e a curva de frequência cardíaca' },
        { title: 'Duas horas sem frequência cardíaca', body: 'O relógio não estava no pulso. O gráfico fica vazio, nunca em 0.' },
      ],
      ask: { question: 'Como eu dormi esta semana em comparação com a anterior?', file: 'ZeppBridge últimos 7 dias.md' },
      starNudge: { title: 'Seu download começou', copy: 'Se o ZeppBridge ajuda você, uma estrela no GitHub ajuda outras pessoas com Amazfit a encontrá-lo.', action: 'Dar uma estrela', dismiss: 'Depois' },
    },
    chapters: { sync: '01 · No seu computador', ai: '02 · Para a sua IA' },
    flap: {
      heading: 'Ele nunca parou de anotar',
      lead: 'Três anos no pulso somam mais ou menos isso. O ZeppBridge traz cada registro de volta e organiza tudo por dia.',
      tiles: [
        { value: '1.096', label: 'noites de sono' },
        { value: '742', label: 'treinos com trajeto' },
        { value: '1,5M', label: 'minutos de frequência cardíaca' },
        { value: '9,8M', label: 'passos' },
      ],
    },
    demo: {
      heading: 'Parece um app, não uma planilha',
      lead: 'Troque de aba para ver outro tipo de dado. Depois mexa no botão e veja como uma medição que faltou deveria aparecer.',
      window: 'ZeppBridge · Visão geral',
      tabs: { heart: 'Frequência', sleep: 'Sono', steps: 'Passos' },
      nav: ['Visão geral', 'Para a IA', 'Treinos', 'Ajustes'],
      heart: { value: '62', unit: 'bpm', caption: 'Minuto a minuto hoje. O pico da noite é uma corrida.' },
      sleep: { value: '7 h 12 min', caption: 'Dormiu às 23:48, acordou às 07:00', stages: ['Acordado', 'REM', 'Leve', 'Profundo'] },
      steps: { value: '11.406', unit: 'passos', caption: 'Passos por hora. As horas sem caminhada ficam vazias.' },
      gap: {
        label: 'Duas horas sem o relógio',
        honest: 'Deixar vazio',
        zero: 'Preencher com 0',
        honestNote: 'É assim que o ZeppBridge desenha: sem dado é sem dado, e a linha se interrompe.',
        zeroNote: 'É assim que muitas ferramentas desenham: uma queda a zero que parece uma emergência.',
      },
    },
    bento: {
      heading: 'Tudo o que precisa. Nada que não precise.',
      lead: 'Cada peça roda no seu computador, sem nenhum servidor nosso no meio.',
      connect: { title: 'Três jeitos de entrar', copy: 'Primeiro a autorização oficial, dados avançados para mais métricas e a entrada manual como plano B.', rows: ['Autorização oficial do Zepp', 'Dados avançados', 'Entrada manual'], states: ['Conectado', 'Conectado', 'Reserva'] },
      local: { title: 'Uma pasta é tudo', copy: 'O banco de dados fica na pasta data ao lado do app. Copie e você tem um backup completo.' },
      export: { title: 'Leve para onde quiser', copy: 'JSON, CSV, GPX e FIT, no período que você escolher.' },
      api: { title: 'Uma porta para scripts e ferramentas de IA', copy: 'Linha de comando, MCP e uma API local só de leitura. Desligada por padrão, só em 127.0.0.1.', output: ['banco de dados   ok', 'última sync      hoje 07:12', 'a recuperar      0 dias'] },
      languages: { title: 'Dez idiomas', copy: 'Português do Brasil e de Portugal, inglês, chinês, espanhol, alemão, francês, holandês, russo e hindi.' },
      theme: { title: 'Escuro primeiro, claro também', copy: 'Segue o sistema ou a sua escolha.', dark: 'Escuro', light: 'Claro' },
    },
    ai: {
      heading: 'Vai perguntar para uma IA? Escolha o que ela pode ver.',
      lead: 'Marque alguns tipos de dado e o ZeppBridge empacota tudo em um arquivo .md. Solte na IA que você já usa e pergunte como perguntaria a um amigo que leu todos os seus registros.',
      pick: 'Desta vez para a IA',
      chips: ['Sono', 'Frequência', 'HRV', 'Treinos', 'Estresse', 'Peso'],
      picked: '{n} tipos escolhidos, últimos 7 dias',
      file: 'ZeppBridge últimos 7 dias.md',
      prompt: 'Eu dormi pior esta semana do que na anterior? O que pode explicar isso?',
      answer: 'Um pouco pior: 38 minutos a menos em média, principalmente de sono profundo. Na terça e na quinta você treinou à noite, e nessas noites seu coração demorou mais para desacelerar. Tente treinar à tarde por uma semana.',
      note: 'Sem IA embutida e sem conta extra. O que vai, quanto e quando só acontece quando você clica.',
    },
    privacy: {
      heading: 'Seus dados de saúde vivem em dois lugares',
      lead: 'Na nuvem do Zepp e no seu próprio computador. Não existe um terceiro.',
      nodes: { watch: 'Relógio', cloud: 'Nuvem do Zepp', computer: 'Seu computador', server: 'Servidor do ZeppBridge', none: 'não existe' },
      points: [
        { title: 'Tokens no cofre do sistema', copy: 'Guardados no Gerenciador de Credenciais do Windows ou nas Chaves do macOS, nunca na pasta de dados.' },
        { title: 'Sem telemetria', copy: 'Nada de rastrear o uso e nenhum dado de saúde coletado.' },
        { title: 'Origem clara', copy: 'Cada registro sabe se veio da autorização oficial ou dos dados avançados.' },
      ],
    },
    connect: {
      heading: 'Três jeitos de conectar. Escolha o mais fácil.',
      lead: 'Comece pela autorização oficial. Adicione os dados avançados quando quiser mais métricas.',
      recommended: 'Recomendado',
      paths: [
        { title: 'Autorização oficial do Zepp', copy: 'Entre no Zepp pelo seu navegador de sempre e autorize.', detail: 'Contas Google, Xiaomi e Apple funcionam. Sono, frequência cardíaca, passos, treinos, PAI e peso são sincronizados.' },
        { title: 'Dados avançados', copy: 'Adiciona HRV, oxigênio no sangue, estresse e prontidão, que a API oficial não oferece.', detail: 'Entre com e-mail ou telefone. O token fica só no cofre do seu sistema.' },
        { title: 'Entrada manual', copy: 'O plano B quando os outros dois não funcionam.', detail: 'Você mesmo cola um token. Pensado para quem conhece a API.' },
      ],
      note: 'O que sincroniza depende do que a sua conta guarda na nuvem do Zepp. As métricas que você vê dependem do seu aparelho e do jeito que você conecta.',
    },
    final: {
      heading: 'Instale e veja do que o seu relógio se lembra',
      lead: 'Grátis, código aberto, sem cadastro.',
      facts: {
        channel: 'Canal estável, instaladores no GitHub Releases',
        systems: 'Windows 10 / 11 (x64) e macOS (Apple Silicon). Linux é experimental.',
        ai: 'Não precisa de outra conta. Para perguntar a uma IA você usa a que já tem.',
        windows: 'Windows: o instalador ainda não é assinado. Se aparecer "Editor desconhecido", escolha "Mais informações" e depois "Executar assim mesmo".',
        macos: 'macOS: uma versão sem assinatura, então a primeira abertura é bloqueada. Os passos para liberar estão no readme do GitHub.',
      },
    },
    footer: {
      tagline: 'Uma ponte local para os dados do Amazfit e do Zepp.',
      disclaimer: 'O ZeppBridge é um projeto independente de código aberto, sem vínculo com a Zepp Health nem com a Amazfit.',
      source: 'Código-fonte',
    },
  },
};

export default pack;
