import type { LandingPack } from '../../composables/useLandingLocale';

const pack: LandingPack = {
  meta: {
    title: 'ZeppBridge · Do pulso para o teu computador, do computador para a IA',
    description: 'O ZeppBridge traz os teus dados Amazfit e Zepp da nuvem Zepp para o teu próprio computador e deixa-os prontos num ficheiro para a tua IA. Gratuito e de código aberto.',
    ogTitle: 'ZeppBridge · Do pulso para a secretária. Da secretária para a IA.',
    ogDescription: 'Sincroniza e consulta localmente a frequência cardíaca, o sono e os treinos, e entrega-os com um clique à IA que já usas.',
  },
  copy: {
    nav: { home: 'Início do ZeppBridge', site: 'Navegação do site', demo: 'Demonstração', features: 'Funcionalidades', ai: 'Para a IA', privacy: 'Privacidade', download: 'Transferir', github: 'GitHub', language: 'Idioma', toDark: 'Mudar para escuro', toLight: 'Mudar para claro' },
    downloads: {
      windows: { label: 'Transferir para Windows', hint: 'Instalador x64', msi: 'MSI para instalações geridas' },
      macos: { label: 'Transferir para macOS', hint: 'Apple Silicon' },
      linux: { label: 'Linux', previewBadge: 'Experimental', note: 'A CI gera deb, rpm, AppImage e Flatpak, mas ninguém testou ainda o início de sessão e o porta-chaves de ponta a ponta num ambiente de trabalho Linux real. Algum problema? Abre uma issue.' },
      status: { loading: 'A procurar o instalador mais recente', ready: 'Clica para transferir diretamente', fallback: 'Abre o GitHub Releases, onde escolhes o instalador' },
    },
    sample: 'Exemplo',
    hero: {
      eyebrow: 'Gratuito · Código aberto · Fica no teu computador',
      titleLead: 'Do pulso para o teu computador.',
      titleAccent: 'Do computador para a IA.',
      lead: 'O ZeppBridge traz da nuvem Zepp a frequência cardíaca, o sono e os treinos que o teu Amazfit registou e guarda-os no teu computador como um arquivo que consegues ler e levar para qualquer lado. Quando tiveres uma pergunta, escolhes um período e entregas a uma IA num único ficheiro.',
      github: 'Ver o código-fonte no GitHub',
      pillars: ['Sincronizado no teu computador', 'Entregue à tua IA com um clique'],
      meta: 'Gratuito · Windows 10 / 11 · macOS (Apple Silicon) · Linux experimental',
      devices: 'Dispositivos Amazfit que já reconhece',
      toasts: [
        { title: 'Sincronização concluída', body: '1284 registos novos, o último de hoje às 07:12' },
        { title: 'Dormiste 7 h 12 min', body: 'Mais 18 minutos de sono profundo do que a tua média de 30 dias' },
        { title: 'Pronto para a tua IA', body: 'Sono, frequência cardíaca e VFC, últimos 7 dias, um ficheiro .md' },
        { title: 'Corrida ao fim do dia, 6,2 km', body: 'Percurso, ritmo por quilómetro e a curva de frequência cardíaca' },
        { title: 'Duas horas sem frequência cardíaca', body: 'O relógio não estava no pulso. O gráfico fica vazio, nunca a 0.' },
      ],
      ask: { question: 'Como dormi esta semana, comparado com a anterior?', file: 'ZeppBridge últimos 7 dias.md' },
      starNudge: { title: 'A transferência começou', copy: 'Se o ZeppBridge te for útil, uma estrela no GitHub ajuda outras pessoas com Amazfit a encontrá-lo.', action: 'Dar uma estrela', dismiss: 'Mais tarde' },
    },
    chapters: { sync: '01 · No teu computador', ai: '02 · Para a tua IA' },
    flap: {
      heading: 'Nunca deixou de tomar nota',
      lead: 'Três anos no pulso dão mais ou menos isto. O ZeppBridge recupera cada registo e arruma-os dia a dia.',
      tiles: [
        { value: '1 096', label: 'noites de sono' },
        { value: '742', label: 'treinos com percurso' },
        { value: '1,5M', label: 'minutos de frequência cardíaca' },
        { value: '9,8M', label: 'passos' },
      ],
    },
    demo: {
      heading: 'Parece uma aplicação, não uma folha de cálculo',
      lead: 'Muda de separador para ver outro tipo de dados. Depois mexe no interruptor e vê como devia aparecer uma medição em falta.',
      window: 'ZeppBridge · Vista geral',
      tabs: { heart: 'Frequência', sleep: 'Sono', steps: 'Passos' },
      nav: ['Vista geral', 'Para a IA', 'Treinos', 'Definições'],
      heart: { value: '62', unit: 'bpm', caption: 'Minuto a minuto hoje. O pico ao fim do dia é uma corrida.' },
      sleep: { value: '7 h 12 min', caption: 'Adormeceste às 23:48 e acordaste às 07:00', stages: ['Acordado', 'REM', 'Leve', 'Profundo'] },
      steps: { value: '11 406', unit: 'passos', caption: 'Passos por hora. As horas sem caminhar ficam vazias.' },
      gap: {
        label: 'Duas horas sem o relógio',
        honest: 'Deixar vazio',
        zero: 'Preencher com 0',
        honestNote: 'É assim que o ZeppBridge desenha: sem dados é sem dados, e a linha interrompe-se.',
        zeroNote: 'É assim que muitas ferramentas desenham: uma queda para zero que parece uma emergência.',
      },
    },
    bento: {
      heading: 'Tudo o que precisa. Nada de que não precise.',
      lead: 'Cada peça corre no teu computador, sem nenhum servidor nosso pelo meio.',
      connect: { title: 'Três maneiras de entrar', copy: 'Primeiro a autorização oficial, dados avançados para mais métricas e a introdução manual como recurso.', rows: ['Autorização oficial Zepp', 'Dados avançados', 'Introdução manual'], states: ['Ligado', 'Ligado', 'Reserva'] },
      local: { title: 'Uma pasta é tudo', copy: 'A base de dados vive na pasta data ao lado da aplicação. Copia-a e tens uma cópia de segurança completa.' },
      export: { title: 'Leva-o para onde quiseres', copy: 'JSON, CSV, GPX e FIT, para o período que escolheres.' },
      api: { title: 'Uma porta para scripts e ferramentas de IA', copy: 'Linha de comandos, MCP e uma API local só de leitura. Desligada por omissão, apenas em 127.0.0.1.', output: ['base de dados   ok', 'última sinc.    hoje 07:12', 'por recuperar   0 dias'] },
      languages: { title: 'Dez idiomas', copy: 'Português europeu e do Brasil, inglês, chinês, espanhol, alemão, francês, neerlandês, russo e hindi.' },
      theme: { title: 'Escuro primeiro, claro também', copy: 'Segue o sistema ou a tua escolha.', dark: 'Escuro', light: 'Claro' },
    },
    ai: {
      heading: 'Vais perguntar a uma IA? Escolhe o que ela pode ver.',
      lead: 'Assinala alguns tipos de dados e o ZeppBridge junta-os num ficheiro .md. Larga-o na IA que já usas e pergunta como perguntarias a um amigo que leu todos os teus registos.',
      pick: 'Desta vez para a IA',
      chips: ['Sono', 'Frequência', 'VFC', 'Treinos', 'Stress', 'Peso'],
      picked: '{n} tipos escolhidos, últimos 7 dias',
      file: 'ZeppBridge últimos 7 dias.md',
      prompt: 'Dormi pior esta semana do que na anterior? O que pode explicar isso?',
      answer: 'Um pouco pior: menos 38 minutos em média, sobretudo de sono profundo. Na terça e na quinta treinaste à noite, e nessas noites o teu coração demorou mais a abrandar. Experimenta treinar à tarde durante uma semana.',
      note: 'Sem IA incorporada e sem conta adicional. O que sai, quanto e quando só acontece quando clicas.',
    },
    privacy: {
      heading: 'Os teus dados de saúde vivem em dois sítios',
      lead: 'Na nuvem Zepp e no teu próprio computador. Não há um terceiro.',
      nodes: { watch: 'Relógio', cloud: 'Nuvem Zepp', computer: 'O teu computador', server: 'Servidor ZeppBridge', none: 'não existe' },
      points: [
        { title: 'Tokens no cofre do sistema', copy: 'Guardados no Gestor de Credenciais do Windows ou no Porta-chaves do macOS, nunca na pasta de dados.' },
        { title: 'Sem telemetria', copy: 'Sem medição de utilização e sem recolha de dados de saúde.' },
        { title: 'Origem clara', copy: 'Cada registo sabe se veio da autorização oficial ou dos dados avançados.' },
      ],
    },
    connect: {
      heading: 'Três maneiras de ligar. Escolhe a mais fácil.',
      lead: 'Começa pela autorização oficial. Junta os dados avançados quando quiseres mais métricas.',
      recommended: 'Recomendado',
      paths: [
        { title: 'Autorização oficial Zepp', copy: 'Inicia sessão no Zepp no teu navegador habitual e autoriza.', detail: 'Funcionam contas Google, Xiaomi e Apple. Sincronizam o sono, a frequência cardíaca, os passos, os treinos, o PAI e o peso.' },
        { title: 'Dados avançados', copy: 'Acrescenta VFC, oxigénio no sangue, stress e prontidão, que a API oficial não oferece.', detail: 'Inicia sessão com e-mail ou telemóvel. O token fica só no cofre do teu sistema.' },
        { title: 'Introdução manual', copy: 'O recurso quando as outras duas não funcionam.', detail: 'Colas tu um token. Pensado para quem conhece a API.' },
      ],
      note: 'O que sincroniza depende do que a tua conta guarda na nuvem Zepp. As métricas que vês dependem do teu dispositivo e da forma como te ligas.',
    },
    final: {
      heading: 'Instala-o e vê do que o teu relógio se lembra',
      lead: 'Gratuito, de código aberto, sem registo.',
      facts: {
        channel: 'Canal estável, instaladores no GitHub Releases',
        systems: 'Windows 10 / 11 (x64) e macOS (Apple Silicon). Linux é experimental.',
        ai: 'Não precisas de outra conta. Para perguntar a uma IA usas a que já tens.',
        windows: 'Windows: o instalador ainda não está assinado. Se vires "Editor desconhecido", escolhe "Mais informações" e depois "Executar mesmo assim".',
        macos: 'macOS: uma versão sem assinatura, por isso a primeira abertura é bloqueada. Os passos para a permitir estão no readme do GitHub.',
      },
    },
    footer: {
      tagline: 'Uma ponte local para os dados Amazfit e Zepp.',
      disclaimer: 'O ZeppBridge é um projeto independente de código aberto, sem ligação à Zepp Health nem à Amazfit.',
      source: 'Código-fonte',
    },
  },
};

export default pack;
